var y=void 0,B=null;function C(){return function(){}}function D(b){return function(){return this[b]}}(function(b){var c={VERSION:"0.2",me:function(){for(var b=document.getElementsByTagName("script"),c=/^(.*\/)leaflet-?([\w-]*)\.js.*$/,f=0,g=b.length;f<g;f++){var h=b[f].src;if(h=h&&h.match(c)){if(h[2]=="include")break;return h[1]}}return"../../dist/"}(),Pk:function(){b.de=this.Nh;return this},Nh:b.de};window.de=c})(this);
L.e={extend:function(b){for(var c=Array.prototype.slice.call(arguments,1),d=0,e=c.length,f;d<e;d++){f=c[d]||{};for(var g in f)f.hasOwnProperty(g)&&(b[g]=f[g])}return b},bind:function(b,c){return function(){return b.apply(c,arguments)}},nb:function(){var b=0;return function(c){c.Se=c.Se||++b;return c.Se}}(),vj:function(){function b(b){window.setTimeout(b,1E3/60)}var c=window.Yk||window.ml||window.Nk||window.Qk||window.Ok||b;return function(d,e,f){d=e?L.e.bind(d,e):e;f&&c===b?d():c(d)}}(),kj:function(b,
c,d){function e(){f=!1;g&&(h.callee.apply(d,h),g=!1)}var f,g,h;return function(){h=arguments;f?g=!0:(f=!0,setTimeout(e,c),b.apply(d,h))}},Mb:function(){return!1},tc:function(b,c){var d=Math.pow(10,c||5);return Math.round(b*d)/d},P:function(b,c){b.options=L.e.extend({},b.options,c)},Xi:function(b){var c=[],d;for(d in b)b.hasOwnProperty(d)&&c.push(d+"="+b[d]);return"?"+c.join("&")}};L.p=C();
L.p.extend=function(b){function c(){!L.p.nf&&this.l&&this.l.apply(this,arguments)}L.p.nf=!0;var d=new this;L.p.nf=!1;d.constructor=c;c.prototype=d;d.Fj=this.prototype;for(var e in this)this.hasOwnProperty(e)&&e!="prototype"&&(c[e]=this[e]);b.Y&&(L.e.extend(c,b.Y),delete b.Y);b.K&&(L.e.extend.apply(B,[d].concat(b.K)),delete b.K);if(b.options&&d.options)b.options=L.e.extend({},d.options,b.options);L.e.extend(d,b);c.extend=arguments.callee;c.ea=function(b){L.e.extend(this.prototype,b)};return c};
L.B={};
L.B.G={addEventListener:function(b,c,d){var e=this.yb=this.yb||{};e[b]=e[b]||[];e[b].push({action:c,Kf:d});return this},xc:function(b){return"_leaflet_events"in this&&b in this.yb&&this.yb[b].length>0},removeEventListener:function(b,c,d){if(!this.xc(b))return this;for(var e=0,f=this.yb,g=f[b].length;e<g;e++)if(f[b][e].action===c&&(!d||f[b][e].Kf===d)){f[b].splice(e,1);break}return this},fireEvent:function(b,c){if(this.xc(b)){for(var d=L.e.extend({type:b,target:this},c),e=this.yb[b].slice(),f=0,g=
e.length;f<g;f++)e[f].action.call(e[f].Kf||this,d);return this}}};L.B.G.n=L.B.G.addEventListener;L.B.G.fa=L.B.G.removeEventListener;L.B.G.h=L.B.G.fireEvent;var F=navigator.userAgent.toLowerCase(),G=!!window.Rj,H=F.indexOf("webkit")!=-1,I=typeof orientation!="undefined"?!0:!1,J=F.indexOf("android")!=-1,M=window.opera;
L.k={cj:G,dj:G&&!window.XMLHttpRequest,Vd:H,yg:H&&"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,Qi:F.indexOf("gecko")!=-1,opera:M,pc:J,hg:I&&H,nj:I&&M,gg:I,ia:"ontouchstart"in document.documentElement};L.j=function(b,c,d){this.x=d?Math.round(b):b;this.y=d?Math.round(c):c};
L.j.prototype={add:function(b){return this.rc().re(b)},re:function(b){this.x+=b.x;this.y+=b.y;return this},F:function(b){return this.rc().wf(b)},wf:function(b){this.x-=b.x;this.y-=b.y;return this},ua:function(b,c){return new L.j(this.x/b,this.y/b,c)},V:function(b){return new L.j(this.x*b,this.y*b)},gb:function(b){var c=b.x-this.x,b=b.y-this.y;return Math.sqrt(c*c+b*b)},round:function(){return this.rc().ic()},ic:function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this},rc:function(){return new L.j(this.x,
this.y)},toString:function(){return"Point("+L.e.tc(this.x)+", "+L.e.tc(this.y)+")"}};
L.Sb=L.p.extend({l:function(b,c){if(b)for(var d=b instanceof Array?b:[b,c],e=0,f=d.length;e<f;e++)this.extend(d[e])},extend:function(b){!this.min&&!this.max?(this.min=new L.j(b.x,b.y),this.max=new L.j(b.x,b.y)):(this.min.x=Math.min(b.x,this.min.x),this.max.x=Math.max(b.x,this.max.x),this.min.y=Math.min(b.y,this.min.y),this.max.y=Math.max(b.y,this.max.y))},Qa:function(b){return new L.j((this.min.x+this.max.x)/2,(this.min.y+this.max.y)/2,b)},contains:function(b){var c;if(b instanceof L.Sb)c=b.min,b=
b.max;return c.x>=this.min.x&&b.x<=this.max.x&&c.y>=this.min.y&&b.y<=this.max.y}});L.Uc=L.p.extend({l:function(b,c,d,e){this.qe=b;this.se=c;this.ue=d;this.Fe=e},transform:function(b,c){return this.zf(b.rc(),c)},zf:function(b,c){c=c||1;b.x=c*(this.qe*b.x+this.se);b.y=c*(this.ue*b.y+this.Fe);return b},Lj:function(b,c){c=c||1;return new L.j((b.x/c-this.se)/this.qe,(b.y/c-this.Fe)/this.ue)}});
L.Ub={Bj:function(b,c){if(!c)return b.slice();b=this.sj(b,c);return this.Pd(b,c)},pj:function(b,c,d){return Math.sqrt(this.uf(b,c,d))},Pd:function(b,c){for(var d=0,e=0,f=1,g=b.length,h;f<g-1;f++)h=this.uf(b[f],b[0],b[g-1]),h>d&&(e=f,d=h);return d>=c*c?(d=b.slice(0,e),e=b.slice(e),g=this.Pd(d,c).slice(0,g-2),e=this.Pd(e,c),g.concat(e)):[b[0],b[g-1]]},sj:function(b,c){for(var d=[b[0]],e=c*c,f=1,g=0,h=b.length;f<h;f++)this.ab(b[f],b[g])<e||(d.push(b[f]),g=f);g<h-1&&d.push(b[h-1]);return d},zi:function(b,
c,d,e){var e=e?this.yh:this.Xa(b,d),f=this.Xa(c,d);for(this.yh=f;;)if(e|f)if(e&f)return!1;else{var g=e||f,h=this.cd(b,c,g,d),j=this.Xa(h,d);g==e?(b=h,e=j):(c=h,f=j)}else return[b,c]},cd:function(b,c,d,e){var f=c.x-b.x,c=c.y-b.y,g=e.min,e=e.max;if(d&8)return new L.j(b.x+f*(e.y-b.y)/c,e.y);else if(d&4)return new L.j(b.x+f*(g.y-b.y)/c,g.y);else if(d&2)return new L.j(e.x,b.y+c*(e.x-b.x)/f);else if(d&1)return new L.j(g.x,b.y+c*(g.x-b.x)/f)},Xa:function(b,c){var d=0;b.x<c.min.x?d|=1:b.x>c.max.x&&(d|=2);
b.y<c.min.y?d|=4:b.y>c.max.y&&(d|=8);return d},ab:function(b,c){var d=c.x-b.x,e=c.y-b.y;return d*d+e*e},uf:function(b,c,d){var e=d.x-c.x,f=d.y-c.y;if(!e&&!f)return this.ab(b,c);var g=((b.x-c.x)*e+(b.y-c.y)*f)/this.ab(c,d);if(g<0)return this.ab(b,c);if(g>1)return this.ab(b,d);c=new L.j(c.x+e*g,c.y+f*g);return this.ab(b,c)}};L.ie={};
L.ie.yi=function(b,c){var d,e=[1,4,2,8],f,g,h,j,l,n,p=L.Ub;f=0;for(l=b.length;f<l;f++)b[f].wb=p.Xa(b[f],c);for(h=0;h<4;h++){n=e[h];d=[];f=0;l=b.length;for(g=l-1;f<l;g=f++)if(j=b[f],g=b[g],j.wb&n){if(!(g.wb&n))g=p.cd(g,j,n,c),g.wb=p.Xa(g,c),d.push(g)}else{if(g.wb&n)g=p.cd(g,j,n,c),g.wb=p.Xa(g,c),d.push(g);d.push(j)}b=d}return b};
L.f={r:function(b,c,d,e){function f(c){return d.call(e||b,c||L.f.oh())}var g=L.e.nb(d);if(L.k.ia&&c=="dblclick"&&this.Hf)this.Hf(b,f,g);else if("addEventListener"in b)if(c=="mousewheel")b.addEventListener("DOMMouseScroll",f,!1),b.addEventListener(c,f,!1);else if(c=="mouseenter"||c=="mouseleave"){var h=f,f=function(c){if(L.f.hh(b,c))return h(c)};b.addEventListener(c=="mouseenter"?"mouseover":"mouseout",f,!1)}else b.addEventListener(c,f,!1);else"attachEvent"in b&&b.attachEvent("on"+c,f);b["_leaflet_"+
c+g]=f},qa:function(b,c,d){var d=L.e.nb(d),e="_leaflet_"+c+d;handler=b[e];L.k.ia&&c=="dblclick"&&this.ng?this.ng(b,d):"removeEventListener"in b?c=="mousewheel"?(b.removeEventListener("DOMMouseScroll",handler,!1),b.removeEventListener(c,handler,!1)):c=="mouseenter"||c=="mouseleave"?b.removeEventListener(c=="mouseenter"?"mouseover":"mouseout",handler,!1):b.removeEventListener(c,handler,!1):"detachEvent"in b&&b.detachEvent("on"+c,handler);b[e]=B},hh:function(b,c){var d=c.relatedTarget;if(!d)return!0;
try{for(;d&&d!=b;)d=d.parentNode}catch(e){return!1}return d!=b},oh:function(){var b=window.event;if(!b)for(var c=arguments.callee.caller;c;){if((b=c.arguments[0])&&Event==b.constructor)break;c=c.caller}return b},stopPropagation:function(b){b.stopPropagation?b.stopPropagation():b.cancelBubble=!0},Lf:function(b){L.f.r(b,"mousedown",L.f.stopPropagation);L.f.r(b,"click",L.f.stopPropagation);L.f.r(b,"dblclick",L.f.stopPropagation)},preventDefault:function(b){b.preventDefault?b.preventDefault():b.returnValue=
!1},stop:function(b){L.f.preventDefault(b);L.f.stopPropagation(b)},Vi:function(b,c){var d=new L.j(b.pageX?b.pageX:b.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,b.pageY?b.pageY:b.clientY+document.body.scrollTop+document.documentElement.scrollTop);return c?d.F(L.c.Ti(c)):d},Zi:function(b){var c=0;b.wheelDelta&&(c=b.wheelDelta/120);b.detail&&(c=-b.detail/3);return c}};
L.e.extend(L.f,{Hf:function(b,c,d){function e(b){if(b.touches.length==1){var c=Date.now(),d=c-(g||c);l=b.touches[0];h=d>0&&d<=j;g=c}}function f(){if(h)l.type="dblclick",c(l),g=B}var g,h=!1,j=250,l;b["_leaflet_touchstart"+d]=e;b["_leaflet_touchend"+d]=f;b.addEventListener("touchstart",e,!1);b.addEventListener("touchend",f,!1)},ng:function(b,c){b.removeEventListener(b,b["_leaflet_touchstart"+c],!1);b.removeEventListener(b,b["_leaflet_touchend"+c],!1)}});
L.c={get:function(b){return typeof b=="string"?document.getElementById(b):b},Id:function(b,c){var d=b.style[c];!d&&b.currentStyle&&(d=b.currentStyle[c]);if(!d||d=="auto")d=(d=document.defaultView.getComputedStyle(b,B))?d[c]:B;return d=="auto"?B:d},Ti:function(b){var c=0,d=0;do c+=b.offsetTop||0,d+=b.offsetLeft||0,b=b.offsetParent;while(b);return new L.j(d,c)},create:function(b,c,d){b=document.createElement(b);b.className=c;d&&d.appendChild(b);return b},Mf:function(){document.selection&&document.selection.empty&&
document.selection.empty();if(!this.sd)this.sd=document.Qb,document.Qb=L.e.Mb},Of:function(){document.Qb=this.sd;this.sd=B},Tj:/(\\s|^)'+cls+'(\\s|$)/,aj:function(b,c){return b.className.length>0&&RegExp("(^|\\s)"+c+"(\\s|$)").test(b.className)},si:function(b,c){L.c.aj(b,c)||(b.className+=(b.className?" ":"")+c)},pg:function(b,c){L.k.cj?b.style.filter="alpha(opacity="+Math.round(c*100)+")":b.style.opacity=c},sg:function(b){for(var c=document.documentElement.style,d=0;d<b.length;d++)if(b[d]in c)return b[d];
return!1},wc:function(b){return L.c.Vg+b.x+"px,"+b.y+"px"+L.c.Ug},Zf:function(b,c){return L.c.wc(c)+" scale("+b+") "+L.c.wc(c.V(-1))},W:function(b,c){b.Ah=c;L.k.Vd?b.style[L.c.Wb]=L.c.wc(c):(b.style.left=c.x+"px",b.style.top=c.y+"px")},N:function(b){return b.Ah}};
L.e.extend(L.c,{ub:L.c.sg(["transition","webkitTransition","OTransition","MozTransition","msTransition"]),Wb:L.c.sg(["transformProperty","WebkitTransform","OTransform","MozTransform","msTransform"]),Vg:"translate"+(L.k.yg?"3d(":"("),Ug:L.k.yg?",0)":")"});
L.ra=L.p.extend({K:L.B.G,Y:{ne:L.k.ia?"touchstart":"mousedown",Tb:L.k.ia?"touchend":"mouseup",ee:L.k.ia?"touchmove":"mousemove",Rg:15},l:function(b,c){this.Je=b;this.He=c||b},enable:function(){if(!this.m)L.f.r(this.He,L.ra.ne,this.Ye,this),this.m=!0},disable:function(){if(this.m)L.f.qa(this.He,L.ra.ne,this.Ye),this.m=!1},Ye:function(b){if(!(b.shiftKey||b.which!=1&&b.button!=1&&!b.touches)&&!(b.touches&&b.touches.length>1)){var c=b.touches&&b.touches.length==1?b.touches[0]:b;L.f.preventDefault(b);
L.k.ia&&(c.target.className+=" leaflet-active");this.sa=!1;L.c.Mf();this.di();this.vf=this.ec=L.c.N(this.Je);this.ji=new L.j(c.clientX,c.clientY);L.f.r(document,L.ra.ee,this.bf,this);L.f.r(document,L.ra.Tb,this.hf,this)}},bf:function(b){if(!(b.touches&&b.touches.length>1)){L.f.preventDefault(b);b=b.touches&&b.touches.length==1?b.touches[0]:b;if(!this.sa)this.h("dragstart"),this.sa=!0;this.ec=this.vf.add(new L.j(b.clientX,b.clientY)).F(this.ji);L.e.vj(this.Fb,this,!0);this.h("drag")}},Fb:function(){L.c.W(this.Je,
this.ec)},hf:function(b){if(b.changedTouches){var b=b.changedTouches[0],c=b.target,d=this.ec&&this.ec.gb(this.vf)||0;c.className=c.className.replace(" leaflet-active","");d<L.ra.Rg&&this.gi("click",b)}L.c.Of();this.bi();L.f.qa(document,L.ra.ee,this.bf);L.f.qa(document,L.ra.Tb,this.hf);this.sa&&this.h("dragend")},fk:C(),di:function(){this.eh=document.body.style.cursor;document.body.style.cursor="move"},bi:function(){document.body.style.cursor=this.eh},gi:function(b,c){var d=document.createEvent("MouseEvent");
d.initMouseEvent(b,!0,!0,window,1,c.screenX,c.screenY,c.clientX,c.clientY,!1,!1,!1,!1,0,B);c.target.dispatchEvent(d)}});L.o=L.p.extend({K:L.B.G,Y:{Yd:{position:L.c.W},ej:function(){return L.o.Rc||L.o.Sg}},options:{Ed:"ease",duration:0.5},ei:function(b,c){var d=L.o.Yd;if(b in d)d[b](this.ca,c);else this.ca.style[b]=c}});var N=L.c.ub;
L.o=L.o.extend({Y:{Rc:!!N,ub:N,he:N+"Property",Eg:N+"Duration",Hg:N+"TimingFunction",Tb:N=="webkitTransition"||N=="OTransition"?N+"End":"transitionend",Dg:{position:L.k.Vd?L.c.Wb:"top, left"}},options:{Mi:100},l:function(b,c){this.ca=b;L.e.P(this,c);L.f.r(b,L.o.Tb,this.gf,this);this.rd=L.e.bind(this.rd,this)},Nd:function(b){var c,d=[],e=L.o.Dg;for(c in b)b.hasOwnProperty(c)&&(c=e[c]?e[c]:c,c=c.replace(/([A-Z])/g,function(b){return"-"+b.toLowerCase()}),d.push(c));this.ca.style[L.o.Eg]=this.options.duration+
"s";this.ca.style[L.o.Hg]=this.options.Ed;this.ca.style[L.o.he]=d.join(", ");for(c in b)b.hasOwnProperty(c)&&this.ei(c,b[c]);this.Me=!0;this.h("start");L.o.Rc?this.cb=setInterval(this.rd,this.options.Mi):this.gf()},rd:function(){this.h("step")},gf:function(){if(this.Me)this.Me=!1,clearInterval(this.cb),this.ca.style[L.o.he]="none",this.h("step"),this.h("end")}});
L.o=L.o.Rc?L.o:L.o.extend({Y:{getTime:Date.now||function(){return+new Date},Sg:!0,ae:{Ji:[0.25,0.1,0.25,1],Jk:[0,0,1,1],"ease-in":[0.42,0,1,1],"ease-out":[0,0,0.58,1],"ease-in-out":[0.42,0,0.58,1]},Cg:{position:L.c.N},Xg:/^[\d\.]+(\D*)$/},options:{Oi:50},l:function(b,c){this.ca=b;L.e.extend(this.options,c);var d=L.o.ae[this.options.Ed]||L.o.ae.Ji;this.Oh=new L.j(0,0);this.Ph=new L.j(d[0],d[1]);this.Qh=new L.j(d[2],d[3]);this.Rh=new L.j(1,1);this.wd=L.e.bind(this.wd,this);this.wh=Math.round(1E3/this.options.Oi)},
Nd:function(b){this.hc={};var c=L.o.Cg,d=L.o.Xg;this.h("start");for(var e in b)if(b.hasOwnProperty(e)){var f={};if(e in c)f.Nb=c[e](this.ca);else{var g=this.ca.style[e].match(d);f.Nb=parseFloat(g[0]);f.Kj=g[1]}f.ug=b[e];this.hc[e]=f}clearInterval(this.cb);this.cb=setInterval(this.wd,this.wh);this.ki=L.o.getTime()},wd:function(){var b=L.o.getTime()-this.ki,c=this.options.duration*1E3;b<c?this.qf(this.mh(b/c)):(this.qf(1),this.kh())},qf:function(b){var c=L.o.Yd,d,e;for(d in this.hc)this.hc.hasOwnProperty(d)&&
(e=this.hc[d],d in c?(e=e.ug.F(e.Nb).V(b).add(e.Nb),c[d](this.ca,e)):this.ca.style[d]=(e.ug-e.Nb)*b+e.Nb+e.Kj);this.h("step")},kh:function(){clearInterval(this.cb);this.h("end")},mh:function(b){var c=3*Math.pow(1-b,2)*b,d=3*(1-b)*Math.pow(b,2),e=Math.pow(b,3),b=this.Oh.V(Math.pow(1-b,3)),c=this.Ph.V(c),d=this.Qh.V(d),e=this.Rh.V(e);return b.add(c).add(d).add(e).y}});
L.u=function(b,c,d){var e=parseFloat(b),f=parseFloat(c);if(isNaN(e)||isNaN(f))throw Error("Invalid LatLng object: ("+b+", "+c+")");d!==!0&&(e=Math.max(Math.min(e,90),-90),f=(f+180)%360+(f<-180?180:-180));this.v=e;this.w=f};L.e.extend(L.u,{$d:Math.PI/180,le:180/Math.PI,$j:1.0E-9});L.u.prototype={toString:function(){return"LatLng("+L.e.tc(this.v)+", "+L.e.tc(this.w)+")"}};
L.sb=L.p.extend({l:function(b,c){if(b)for(var d=b instanceof Array?b:[b,c],e=0,f=d.length;e<f;e++)this.extend(d[e])},extend:function(b){!this.U&&!this.S?(this.U=new L.u(b.v,b.w),this.S=new L.u(b.v,b.w)):(this.U.v=Math.min(b.v,this.U.v),this.U.w=Math.min(b.w,this.U.w),this.S.v=Math.max(b.v,this.S.v),this.S.w=Math.max(b.w,this.S.w))},Qa:function(){return new L.u((this.U.v+this.S.v)/2,(this.U.w+this.S.w)/2)},Ck:D("U"),zk:D("S"),Wi:function(){return new L.u(this.S.v,this.U.w)},Yi:function(){return new L.u(this.U.v,
this.S.w)},contains:function(b){var c=this.U,d=this.S,e;b instanceof L.sb?(e=b.U,b=b.S):e=b;return e.v>=c.v&&b.v<=d.v&&e.w>=c.w&&b.w<=d.w}});L.Ka={};L.Ka.Qg={Pc:85.0511287798,O:function(b){var c=L.u.$d,d=this.Pc,e=b.w*c,b=Math.max(Math.min(d,b.v),-d)*c,b=Math.log(Math.tan(Math.PI/4+b/2));return new L.j(e,b)},aa:function(b,c){var d=L.u.le;return new L.u((2*Math.atan(Math.exp(b.y))-Math.PI/2)*d,b.x*d,c)}};L.Ka.Kg={O:function(b){return new L.j(b.w,b.v)},aa:function(b,c){return new L.u(b.y,b.x,c)}};
L.Ka.ge={Pc:85.0840591556,Tc:6356752.3142,Sc:6378137,O:function(b){var c=L.u.$d,d=this.Pc,e=this.Sc,f=b.w*c*e,b=Math.max(Math.min(d,b.v),-d)*c,c=this.Tc/e,c=Math.sqrt(1-c*c),d=c*Math.sin(b),d=Math.pow((1-d)/(1+d),c*0.5),b=-e*Math.log(Math.tan(0.5*(Math.PI*0.5-b))/d);return new L.j(f,b)},aa:function(b,c){for(var d=L.u.le,e=this.Sc,f=b.x*d/e,g=this.Tc/e,g=Math.sqrt(1-g*g),e=Math.exp(-b.y/e),h=Math.PI/2-2*Math.atan(e),j=15,l=0.1;Math.abs(l)>1.0E-7&&--j>0;)l=g*Math.sin(h),l=Math.PI/2-2*Math.atan(e*Math.pow((1-
l)/(1+l),0.5*g))-h,h+=l;return new L.u(h*d,f,c)}};L.ka={ij:function(b,c){return this.Jc.zf(this.lb.O(b),c)},oj:function(b,c,d){return this.lb.aa(this.Jc.Lj(b,c),d)},O:function(b){return this.lb.O(b)}};L.ka.be=L.e.extend({},L.ka,{code:"EPSG:3857",lb:L.Ka.Qg,Jc:new L.Uc(0.5/Math.PI,0.5,-0.5/Math.PI,0.5),O:function(b){return this.lb.O(b).V(6378137)}});L.ka.Wj=L.e.extend({},L.ka.be,{code:"EPSG:900913"});L.ka.Ig=L.e.extend({},L.ka,{code:"EPSG:4326",lb:L.Ka.Kg,Jc:new L.Uc(1/360,0.5,-1/360,0.5)});
L.ka.Vj=L.e.extend({},L.ka,{code:"EPSG:3395",lb:L.Ka.ge,Jc:function(){var b=L.Ka.ge;return new L.Uc(0.5/(Math.PI*b.Sc),0.5,-0.5/(Math.PI*b.Tc),0.5)}()});
L.Oc=L.p.extend({l:function(b){this.s={};if(b)for(var c=0,d=b.length;c<d;c++)this.ma(b[c])},ma:function(b){this.s[L.e.nb(b)]=b;this.a&&this.a.ma(b);return this},mb:function(b){delete this.s[L.e.nb(b)];this.a&&this.a.mb(b);return this},pk:function(){this.md(this.mb,this);return this},ga:function(b){this.a=b;this.md(b.ma,b)},Ga:function(b){this.md(b.mb,b);delete this.a},md:function(b,c){for(var d in this.s)this.s.hasOwnProperty(d)&&b.call(c,this.s[d])}});
L.Nc=L.Oc.extend({K:L.B.G,ma:function(b){this.Ya(b);L.Oc.prototype.ma.call(this,b);this.lf&&b.fb&&b.fb(this.lf)},fb:function(b){this.lf=b;for(var c in this.s)this.s.hasOwnProperty(c)&&this.s[c].fb&&this.s[c].fb(b)},Ke:["click","dblclick","mouseover","mouseout"],Ya:function(b){for(var c=0,d=this.Ke.length;c<d;c++)b.n(this.Ke[c],this.Vh,this)},Vh:function(b){b.Ac=b.target;b.target=this;this.h(b.type,b)}});
L.ba=L.p.extend({K:L.B.G,options:{Pb:0,Ob:18,Ta:256,Rb:"abc",Ki:"",qc:"",opacity:1,scheme:"xyz",noWrap:!1,wg:L.k.gg,Ud:L.k.gg},l:function(b,c){L.e.P(this,c);this.Gb=b;if(typeof this.options.Rb=="string")this.options.Rb=this.options.Rb.split("")},ga:function(b){this.a=b;this.Ne();this.Ee();b.n("viewreset",this.Z,this);this.options.Ud?b.n("moveend",this.$,this):(this.Te=L.e.kj(this.$,150,this),b.n("move",this.Te,this));this.Z();this.$()},Ga:function(){this.a.C.Rd.removeChild(this.b);this.b=B;this.a.fa("viewreset",
this.Z,this);this.options.Ud?this.a.fa("moveend",this.$,this):this.a.fa("move",this.Te,this)},Rf:function(){return this.options.qc},pg:function(b){this.options.opacity=b;this.rf(b);if(L.k.Vd)for(i in this.la)this.la[i].style.webkitTransform+=" translate(0,0)"},rf:function(b){b<1&&L.c.pg(this.b,b)},Ne:function(){var b=this.a.C.Rd;if(!this.b||b.empty)this.b=L.c.create("div","leaflet-layer",b),this.rf(this.options.opacity)},Z:function(){this.la={};this.Ne();this.b.innerHTML=""},$:function(){var b=this.a.Gd(),
c=this.options.Ta,d=new L.j(Math.floor(b.min.x/c),Math.floor(b.min.y/c)),b=new L.j(Math.floor(b.max.x/c),Math.floor(b.max.y/c)),d=new L.Sb(d,b);this.$g(d);this.options.wg&&this.Xh(d)},$g:function(b){for(var c=[],d=b.Qa(),e=b.min.y;e<=b.max.y;e++)for(var f=b.min.x;f<=b.max.x;f++)f+":"+e in this.la||c.push(new L.j(f,e));c.sort(function(b,c){return b.gb(d)-c.gb(d)});b=document.createDocumentFragment();this.xd=c.length;e=0;for(f=this.xd;e<f;e++)this.Zg(c[e],b);this.b.appendChild(b)},Xh:function(b){var c,
d,e;for(e in this.la)if(this.la.hasOwnProperty(e)&&(c=e.split(":"),d=parseInt(c[0],10),c=parseInt(c[1],10),d<b.min.x||d>b.max.x||c<b.min.y||c>b.max.y))this.la[e].src="",this.la[e].parentNode==this.b&&this.b.removeChild(this.la[e]),delete this.la[e]},Zg:function(b,c){var d=this.ph(b),e=this.a.z,f=b.x+":"+b.y,g=1<<e;if(!this.options.noWrap)b.x=(b.x%g+g)%g;if(!(b.y<0||b.y>=g)){var h=this.De();L.c.W(h,d);this.la[f]=h;if(this.options.scheme=="tms")b.y=g-b.y-1;this.Ue(h,b,e);c.appendChild(h)}},ph:function(b){return b.V(this.options.Ta).F(this.a.Ma)},
$f:function(b,c){return this.Gb.replace("{s}",this.options.Rb[(b.x+b.y)%this.options.Rb.length]).replace("{z}",c).replace("{x}",b.x).replace("{y}",b.y)},Ee:function(){this.lc=L.c.create("img","leaflet-tile");this.lc.Pi="no";var b=this.options.Ta;this.lc.style.width=b+"px";this.lc.style.height=b+"px"},De:function(){var b=this.lc.cloneNode(!1);b.Qb=b.onmousemove=L.e.Mb;return b},Ue:function(b,c,d){b.nd=this;b.onload=this.yf;b.onerror=this.mi;b.src=this.$f(c,d)},yf:function(){var b=this.nd;this.className+=
" leaflet-tile-loaded";b.h("tileload",{Hj:this,url:this.src});b.xd--;b.xd||b.h("load")},mi:function(){var b=this.nd;b.h("tileerror",{Hj:this,url:this.src});if(b=b.options.Ki)this.src=b}});
L.ba.bk=L.ba.extend({Hi:{$k:"WMS",Xk:"GetMap",version:"1.1.1",dg:"",ob:"",sk:"image/jpeg",kl:!1},l:function(b,c){this.Gb=b;this.qb=L.e.extend({},this.Hi);this.qb.width=this.qb.height=this.options.Ta;for(var d in c)this.options.hasOwnProperty(d)||(this.qb[d]=c[d]);L.e.P(this,c)},ga:function(b){this.qb[parseFloat(this.qb.version)>=1.3?"crs":"srs"]=b.options.Lb.code;L.ba.prototype.ga.call(this,b)},$f:function(b){var c=this.options.Ta,b=b.V(c),c=b.add(new L.j(c,c)),b=this.a.aa(b,this.z,!0),c=this.a.aa(c,
this.z,!0),b=this.a.options.Lb.O(b),c=this.a.options.Lb.O(c),c=[b.x,c.y,c.x,b.y].join(",");return this.Gb+L.e.Xi(this.qb)+"&bbox="+c}});L.ba.Ja=L.ba.extend({options:{async:!1},l:function(b){L.e.P(this,b)},Ee:function(){this.Vc=L.c.create("canvas","leaflet-tile");var b=this.options.Ta;this.Vc.width=b;this.Vc.height=b},De:function(){var b=this.Vc.cloneNode(!1);b.Qb=b.onmousemove=L.e.Mb;return b},Ue:function(b,c,d){b.nd=this;this.Nf(b,c,d);this.options.async||this.tg(b)},Nf:C(),tg:function(b){this.yf.call(b)}});
L.Xj=L.p.extend({K:L.B.G,l:function(b,c){this.Gb=b;this.te=c},ga:function(b){this.a=b;this.Ba||this.th();b.C.Sa.appendChild(this.Ba);b.n("viewreset",this.Z,this);this.Z()},Ga:function(b){b.C.Sa.removeChild(this.Ba);b.fa("viewreset",this.Z,this)},th:function(){this.Ba=L.c.create("img","leaflet-image-layer");this.Ba.style.visibility="hidden";L.e.extend(this.Ba,{Pi:"no",Qb:L.e.Mb,onmousemove:L.e.Mb,onload:this.Gh,src:this.Gb})},Z:function(){var b=this.a.Fa(this.te.Wi()),c=this.a.Fa(this.te.Yi()).F(b);
L.c.W(this.Ba,b);this.Ba.style.width=c.x+"px";this.Ba.style.height=c.y+"px"},Gh:function(){this.style.visibility=""}});
L.je=L.p.extend({K:L.B.G,options:{maxWidth:300,ti:!0,Ai:!0,Dc:new L.j(0,2),ui:new L.j(5,5)},l:function(b){L.e.P(this,b)},ga:function(b){this.a=b;this.b||this.jd();this.Bf();this.b.style.opacity="0";this.a.C.mg.appendChild(this.b);this.a.n("viewreset",this.Fb,this);this.a.options.Bi&&this.a.n("preclick",this.Zb,this);this.$();this.b.style.opacity="1";this.fc=!0},Ga:function(b){b.C.mg.removeChild(this.b);b.fa("viewreset",this.Fb,this);b.fa("click",this.Zb,this);this.b.style.opacity="0";this.fc=!1},
Gc:function(b){this.da=b;this.fc&&this.$();return this},og:function(b){this.ac=b;this.fc&&this.$();return this},Zb:function(){this.fc&&this.a.mb(this)},jd:function(){this.b=L.c.create("div","leaflet-popup");if(this.options.Ai)this.xe=L.c.create("a","leaflet-popup-close-button",this.b),this.xe.href="#close",this.xe.onclick=L.e.bind(this.Fh,this);this.Ef=L.c.create("div","leaflet-popup-content-wrapper",this.b);L.f.Lf(this.Ef);this.ad=L.c.create("div","leaflet-popup-content",this.Ef);this.ni=L.c.create("div",
"leaflet-popup-tip-container",this.b);this.gk=L.c.create("div","leaflet-popup-tip",this.ni)},$:function(){this.b.style.visibility="hidden";this.Bf();this.oi();this.Fb();this.b.style.visibility="";this.ah()},Bf:function(){if(this.ac)typeof this.ac=="string"?this.ad.innerHTML=this.ac:(this.ad.innerHTML="",this.ad.appendChild(this.ac))},oi:function(){this.b.style.width="";this.b.style.whiteSpace="nowrap";var b=this.b.offsetWidth;this.b.style.width=(b>this.options.maxWidth?this.options.maxWidth:b)+"px";
this.b.style.whiteSpace="";this.$c=this.b.offsetWidth},Fb:function(){var b=this.a.Fa(this.da);this.ye=-b.y-this.options.Dc.y;this.ze=b.x-Math.round(this.$c/2)+this.options.Dc.x;this.b.style.bottom=this.ye+"px";this.b.style.left=this.ze+"px"},ah:function(){if(this.options.ti){var b=this.b.offsetHeight,c=this.a.jj(new L.j(this.ze,-b-this.ye)),d=new L.j(0,0),e=this.options.ui,f=this.a.na();if(c.x<0)d.x=c.x-e.x;if(c.x+this.$c>f.x)d.x=c.x+this.$c-f.x+e.x;if(c.y<0)d.y=c.y-e.y;if(c.y+b>f.y)d.y=c.y+b-f.y+
e.y;(d.x||d.y)&&this.a.Jd(d)}},Fh:function(b){this.Zb();L.f.stop(b)}});
L.Jg=L.p.extend({bj:L.me+"images/marker.png",gl:L.me+"images/marker-shadow.png",Hk:new L.j(25,41),fl:new L.j(41,41),ag:new L.j(13,41),qj:new L.j(0,-33),l:function(b){if(b)this.bj=b},Di:function(){return this.Ce("icon")},Ei:function(){return this.Ce("shadow")},Ce:function(b){var c=this[b+"Size"],d=this[b+"Url"],e=this.lh(d);if(!d)return B;e.className="leaflet-marker-"+b;e.style.marginLeft=-this.ag.x+"px";e.style.marginTop=-this.ag.y+"px";if(c)e.style.width=c.x+"px",e.style.height=c.y+"px";return e},
lh:function(b){var c;L.k.dj?(c=document.createElement("div"),c.style.filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+b+'")'):(c=document.createElement("img"),c.src=b);return c}});
L.Qc=L.p.extend({K:L.B.G,options:{yc:new L.Jg,title:"",Jb:!0,draggable:!1},l:function(b,c){L.e.P(this,c);this.da=b},ga:function(b){this.a=b;this.Pe();b.n("viewreset",this.Z,this);this.Z()},Ga:function(b){this.of();b.fa("viewreset",this.Z,this)},xk:D("da"),Gc:function(b){this.da=b;this.Z()},al:function(b){this.of();this.Q=this.ta=B;this.options.yc=b;this.Pe()},Pe:function(){if(!this.Q){this.Q=this.options.yc.Di();if(this.options.title)this.Q.title=this.options.title;this.hd()}if(!this.ta)this.ta=this.options.yc.Ei();
this.a.C.fg.appendChild(this.Q);this.ta&&this.a.C.rg.appendChild(this.ta)},of:function(){this.a.C.fg.removeChild(this.Q);this.ta&&this.a.C.rg.removeChild(this.ta)},Z:function(){var b=this.a.Fa(this.da).round();L.c.W(this.Q,b);this.ta&&L.c.W(this.ta,b);this.Q.style.zIndex=b.y},hd:function(){if(this.options.Jb){this.Q.className+=" leaflet-clickable";L.f.r(this.Q,"click",this.zb,this);for(var b=["dblclick","mousedown","mouseover","mouseout"],c=0;c<b.length;c++)L.f.r(this.Q,b[c],this.La,this)}if(L.t.fe)this.va=
new L.t.fe(this),this.options.draggable&&this.va.enable()},zb:function(b){L.f.stopPropagation(b);(!this.va||!this.va.Cc())&&this.h(b.type)},La:function(b){this.h(b.type);L.f.stopPropagation(b)}});L.Qc.ea({Ec:function(){this.M.Gc(this.da);this.a.Ec(this.M);return this},Ad:function(){this.M&&this.M.Zb()},fb:function(b,c){c=L.e.extend({Dc:this.options.yc.qj},c);this.M=new L.je(c);this.M.og(b);this.n("click",this.Ec,this);return this}});
L.q=L.p.extend({K:[L.B.G],Y:{Xd:0.5},options:{stroke:!0,color:"#0033ff",Ua:5,opacity:0.5,fill:!1,fillColor:B,Fd:0.2,Jb:!0,Td:!1},l:function(b){L.e.P(this,b)},ga:function(b){this.a=b;this.gd();this.Ya();this.Ha();this.Ca();b.n("viewreset",this.Ha,this);this.Df=this.options.Td?"moveend":"viewreset";b.n(this.Df,this.Ca,this)},Ga:function(b){b.T.removeChild(this.b);b.fa("viewreset",this.ek,this);b.fa(this.Df,this.Ca,this)},Ha:C(),Od:function(b){L.e.P(this,b);this.b&&this.eb()},gd:function(){this.xb();
this.kd();this.ld()},nc:function(){var b=L.q.Xd,c=this.a.na(),d=L.c.N(this.a.A).V(-1).F(c.V(b)),b=d.add(c.V(1+b*2));this.a.Ab=new L.Sb(d,b)},$a:function(){this.Ha();this.Ca()}});L.q.ea({fb:function(b,c){if(!this.M||this.M.options!==c)this.M=new L.je(c);this.M.og(b);if(!this.Mh)this.n("click",this.Lh,this),this.Mh=!0;return this},Lh:function(b){this.M.Gc(b.zc);this.a.Ec(this.M)}});L.q.pe="http://www.w3.org/2000/svg";L.k.Ic=!(!document.createElementNS||!document.createElementNS(L.q.pe,"svg").qk);
L.q=L.q.extend({Y:{oe:L.k.Ic},vc:C(),gd:function(){this.xb();this.kd();this.ld()},xb:function(){if(!this.a.T)this.a.T=this.za("svg"),this.a.C.Sa.appendChild(this.a.T),this.a.n("moveend",this.Cf,this),this.Cf()},Cf:function(){this.nc();var b=this.a.Ab,c=b.min,d=b.max,b=d.x-c.x,d=d.y-c.y,e=this.a.T,f=this.a.C.Sa;L.k.hg&&f.removeChild(e);L.c.W(e,c);e.setAttribute("width",b);e.setAttribute("height",d);e.setAttribute("viewBox",[c.x,c.y,b,d].join(" "));L.k.hg&&f.appendChild(e)},kd:function(){this.b=this.za("g");
this.J=this.za("path");this.b.appendChild(this.J);this.a.T.appendChild(this.b)},ld:function(){this.options.stroke&&(this.J.setAttribute("stroke-linejoin","round"),this.J.setAttribute("stroke-linecap","round"));this.options.fill?this.J.setAttribute("fill-rule","evenodd"):this.J.setAttribute("fill","none");this.eb()},eb:function(){this.options.stroke&&(this.J.setAttribute("stroke",this.options.color),this.J.setAttribute("stroke-opacity",this.options.opacity),this.J.setAttribute("stroke-width",this.options.Ua));
this.options.fill&&(this.J.setAttribute("fill",this.options.fillColor||this.options.color),this.J.setAttribute("fill-opacity",this.options.Fd))},Ca:function(){var b=this.vc();b||(b="M0 0");this.J.setAttribute("d",b)},za:function(b){return document.createElementNS(L.q.pe,b)},Ya:function(){if(this.options.Jb){L.k.xg||this.J.setAttribute("class","leaflet-clickable");L.f.r(this.b,"click",this.zb,this);for(var b=["dblclick","mousedown","mouseover","mouseout"],c=0;c<b.length;c++)L.f.r(this.b,b[c],this.La,
this)}},zb:function(b){(!this.a.va||!this.a.va.Cc())&&this.La(b)},La:function(b){this.xc(b.type)&&(this.h(b.type,{zc:this.a.jg(b),cg:this.a.oa(b)}),L.f.stopPropagation(b))}});var O=L.k,P=document.createElement("div");P.innerHTML='<v:shape adj="1"/>';P=P.firstChild;P.style.kk="url(#default#VML)";O.xg=P&&typeof P.ik=="object";
L.q=L.k.Ic||!L.k.xg?L.q:L.q.extend({Y:{Yg:!0,Xd:0.02},za:function(){try{return document.namespaces.add("lvml","urn:schemas-microsoft-com:vml"),function(b){return document.createElement("<lvml:"+b+' class="lvml">')}}catch(b){return function(b){return document.createElement("<"+b+' xmlns="urn:schemas-microsoft.com:vml" class="lvml">')}}}(),xb:function(){if(!this.a.T)this.a.T=document.createElement("div"),this.a.T.className="leaflet-vml-container",this.a.C.Sa.appendChild(this.a.T),this.a.n("moveend",
this.nc,this),this.nc()},kd:function(){this.b=this.za("shape");this.b.className+=" leaflet-vml-shape"+(this.options.Jb?" leaflet-clickable":"");this.b.coordsize="1 1";this.J=this.za("path");this.b.appendChild(this.J);this.a.T.appendChild(this.b)},ld:function(){this.options.stroke?(this.Db=this.za("stroke"),this.Db.rk="round",this.b.appendChild(this.Db)):this.b.stroked=!1;this.options.fill?(this.b.filled=!0,this.bd=this.za("fill"),this.b.appendChild(this.bd)):this.b.filled=!1;this.eb()},eb:function(){if(this.options.stroke)this.Db.Ua=
this.options.Ua+"px",this.Db.color=this.options.color,this.Db.opacity=this.options.opacity;if(this.options.fill)this.bd.color=this.options.fillColor||this.options.color,this.bd.opacity=this.options.Fd},Ca:function(){this.b.style.display="none";this.J.ll=this.vc()+" ";this.b.style.display=""}});L.k.canvas=!!document.createElement("canvas").getContext;
L.q=L.q.oe&&!window.Zj||!L.k.canvas?L.q:L.q.extend({Y:{Lc:!0,oe:!1},options:{Td:!0},gd:function(){this.xb()},xb:function(){var b=this.a.T,c=this.a.fh;if(!b)b=this.a.T=document.createElement("canvas"),b.style.position="absolute",c=this.a.fh=b.getContext("2d"),c.lineCap="round",c.lineJoin="round",this.a.C.Sa.appendChild(b),this.a.n("moveend",this.Af,this),this.Af();this.L=c},eb:function(){if(this.options.stroke)this.L.lineWidth=this.options.Ua,this.L.strokeStyle=this.options.color;if(this.options.fill)this.L.fillStyle=
this.options.fillColor||this.options.color},Ie:function(){var b,c,d,e,f,g;this.L.beginPath();b=0;for(d=this.I.length;b<d;b++){c=0;for(e=this.I[b].length;c<e;c++)f=this.I[b][c],g=(c===0?"move":"line")+"To",this.L[g](f.x,f.y);this instanceof L.Vb&&this.L.closePath()}},Yc:function(){return!this.I.length},Ca:function(){if(!this.Yc()){this.Ie();this.L.save();this.eb();var b=this.options.opacity,c=this.options.Fd;if(this.options.fill){if(c<1)this.L.globalAlpha=c;this.L.fill()}if(this.options.stroke){if(b<
1)this.L.globalAlpha=b;this.L.stroke()}this.L.restore()}},Af:function(){this.nc();var b=this.a.Ab,c=b.min,b=b.max.F(c),d=this.a.T;L.c.W(d,c);d.width=b.x;d.height=b.y;d.getContext("2d").translate(-c.x,-c.y)},Ya:function(){this.options.Jb&&this.a.n("click",this.Eh,this)},Eh:function(b){this.$b(b.cg)&&this.h("click",b)}});
L.xa=L.q.extend({l:function(b,c){L.q.prototype.l.call(this,c);this.Na=b},options:{Cj:1,kg:!1,Td:!0},Ha:function(){this.td=[];for(var b=0,c=this.Na.length;b<c;b++)this.td[b]=this.a.Fa(this.Na[b])},vc:function(){for(var b=0,c=this.I.length,d="";b<c;b++)d+=this.dd(this.I[b]);return d},yk:D("Na"),bl:function(b){this.Na=b;this.$a();return this},hk:function(b){this.Na.push(b);this.$a();return this},hl:function(){var b=[].splice.apply(this.Na,arguments);this.$a();return b},dd:function(b){for(var c=L.q.Yg,
d=0,e=b.length,f="",g;d<e;d++)g=b[d],c&&g.ic(),f+=(d?"L":"M")+g.x+" "+g.y;return f},we:function(){var b=this.td,c=b.length,d,e,f;if(this.options.kg)this.I=[b];else{var g=this.I=[],h=this.a.Ab,j=L.Ub;for(e=d=0;d<c-1;d++)if(f=j.zi(b[d],b[d+1],h,d))if(g[e]=g[e]||[],g[e].push(f[0]),f[1]!=b[d+1]||d==c-2)g[e].push(f[1]),e++}},fi:function(){for(var b=this.I,c=L.Ub,d=0,e=b.length;d<e;d++)b[d]=c.Bj(b[d],this.options.Cj)},Ca:function(){this.we();this.fi();L.q.prototype.Ca.call(this)}});
L.xa.ea(!L.q.Lc?{}:{$b:function(b,c){var d,e,f,g,h,j,l=this.options.Ua/2;L.k.ia&&(l+=10);d=0;for(g=this.I.length;d<g;d++){j=this.I[d];e=0;h=j.length;for(f=h-1;e<h;f=e++)if(c||e!==0)if(f=L.Ub.pj(b,j[f],j[e]),f<=l)return!0}return!1}});
L.Vb=L.xa.extend({options:{fill:!0},l:function(b,c){L.xa.prototype.l.call(this,b,c);if(b[0]instanceof Array)this.Na=b[0],this.bc=b.slice(1)},Ha:function(){L.xa.prototype.Ha.call(this);this.fd=[];if(this.bc)for(var b=0,c=this.bc.length;b<c;b++){this.fd[b]=[];for(var d=0,e=this.bc[b].length;d<e;d++)this.fd[b][d]=this.a.Fa(this.bc[b][d])}},we:function(){var b=[];this.I=[this.td].concat(this.fd);if(!this.options.kg){for(var c=0,d=this.I.length;c<d;c++){var e=L.ie.yi(this.I[c],this.a.Ab);e.length&&b.push(e)}this.I=
b}},dd:function(b){return L.xa.prototype.dd.call(this,b)+(L.k.Ic?"z":"x")}});L.Vb.ea(!L.q.Lc?{}:{$b:function(b){var c=!1,d,e,f,g,h,j,l;if(L.xa.prototype.$b.call(this,b,!0))return!0;g=0;for(j=this.I.length;g<j;g++){d=this.I[g];h=0;l=d.length;for(f=l-1;h<l;f=h++)e=d[h],f=d[f],e.y>b.y!=f.y>b.y&&b.x<(f.x-e.x)*(b.y-e.y)/(f.y-e.y)+e.x&&(c=!c)}return c}});
(function(){function b(b){return L.Nc.extend({l:function(d,e){this.s={};for(var f=0,g=d.length;f<g;f++)this.ma(new b(d[f],e))},Od:function(b){for(var c in this.s)this.s.hasOwnProperty(c)&&this.s[c].Od&&this.s[c].Od(b)}})}L.Ng=b(L.xa);L.Mg=b(L.Vb)})();
L.Mc=L.q.extend({l:function(b,c,d){L.q.prototype.l.call(this,d);this.da=b;this.Ve=c},options:{fill:!0},Gc:function(b){this.da=b;this.$a();return this},xj:function(b){this.Ve=b;this.$a();return this},Ha:function(){var b=this.a.options.scale(this.a.z);this.Bb=this.a.Fa(this.da);this.Za=this.Ve/40075017*b},vc:function(){var b=this.Bb,c=this.Za;if(this.Yc())return"";return L.k.Ic?"M"+b.x+","+(b.y-c)+"A"+c+","+c+",0,1,1,"+(b.x-0.1)+","+(b.y-c)+" z":(b.ic(),c=Math.round(c),"AL "+b.x+","+b.y+" "+c+","+c+
" 0,23592600")},Yc:function(){var b=this.a.Ab,c=this.Za,d=this.Bb;return d.x-c>b.max.x||d.y-c>b.max.y||d.x+c<b.min.x||d.y+c<b.min.y}});L.Mc.ea(!L.q.Lc?{}:{Ie:function(){var b=this.Bb;this.L.beginPath();this.L.arc(b.x,b.y,this.Za,0,Math.PI*2)},$b:function(b){return b.gb(this.Bb)<=this.Za+(this.options.stroke?this.options.Ua/2:0)}});
L.Uj=L.Mc.extend({options:{rj:10,Ua:2},l:function(b,c){L.Mc.prototype.l.call(this,b,B,c);this.Za=this.options.rj},Ha:function(){this.Bb=this.a.Fa(this.da)},xj:function(b){this.Za=b;this.$a();return this}});L.ce=L.Oc.extend({K:L.B.G,l:function(b,c){L.e.P(this,c);this.dk=b;this.s={};b&&this.If(b)},If:function(b){if(b.ib)for(var c=0,d=b.ib.length;c<d;c++)this.If(b.ib[c]);else c=b.type=="Feature"?b.tk:b,d=L.ce.Qf(c,this.options.Vk),this.h("featureparse",{Ac:d,Ld:b.Ld,uk:c.type,vi:b.vi,id:b.id}),this.ma(d)}});
L.e.extend(L.ce,{Qf:function(b,c){var d=b.Da,e,f,g,h=[];switch(b.type){case "Point":return e=this.Cd(d),c?c(e):new L.Qc(e);case "MultiPoint":f=0;for(g=d.length;f<g;f++)e=this.Cd(d[f]),e=c?c(e):new L.Qc(e),h.push(e);return new L.Nc(h);case "LineString":return d=this.Kb(d),new L.xa(d);case "Polygon":return d=this.Kb(d,1),new L.Vb(d);case "MultiLineString":return d=this.Kb(d,1),new L.Ng(d);case "MultiPolygon":return d=this.Kb(d,2),new L.Mg(d);case "GeometryCollection":f=0;for(g=b.Ri.length;f<g;f++)e=
this.Qf(b.Ri[f]),h.push(e);return new L.Nc(h);default:throw Error("Invalid GeoJSON object.");}},Cd:function(b,c){return new L.u(parseFloat(b[c?0:1]),parseFloat(b[c?1:0]))},Kb:function(b,c,d){var e,f=[],g,h=b.length;for(g=0;g<h;g++)e=c?this.Kb(b[g],c-1,d):this.Cd(b[g],d),f.push(e);return f}});L.t=L.p.extend({l:function(b){this.a=b},enabled:function(){return!!this.m}});
L.t.Lg=L.t.extend({enable:function(){if(!this.m){if(!this.H)this.H=new L.ra(this.a.A,this.a.b),this.H.n("dragstart",this.qd,this),this.H.n("drag",this.od,this),this.H.n("dragend",this.pd,this);this.H.enable();this.m=!0}},disable:function(){if(this.m)this.H.disable(),this.m=!1},Cc:function(){return this.H.sa},qd:function(){this.a.h("movestart");this.a.h("dragstart")},od:function(){this.a.h("move");this.a.h("drag")},pd:function(){this.a.h("moveend");this.a.h("dragend")}});
L.t.Wg=L.t.extend({enable:function(){if(L.k.ia&&!this.m)L.f.r(this.a.b,"touchstart",this.ff,this),this.m=!0},disable:function(){if(this.m)L.f.qa(this.a.b,"touchstart",this.ff,this),this.m=!1},ff:function(b){if(b.touches&&!(b.touches.length!=2||this.a.Xb)){var c=this.a.oa(b.touches[0]),d=this.a.oa(b.touches[1]),e=this.a.Bd(this.a.na().ua(2));this.Cb=c.add(d).ua(2,!0);this.ii=c.gb(d);this.sa=!1;this.yd=!0;this.gh=e.F(this.Cb);L.f.r(document,"touchmove",this.ef,this);L.f.r(document,"touchend",this.df,
this);L.f.preventDefault(b)}},ef:function(b){if(b.touches&&b.touches.length==2){if(!this.sa)this.a.A.className+=" leaflet-zoom-anim",this.a.mf(),this.sa=!0;var c=this.a.oa(b.touches[0]),d=this.a.oa(b.touches[1]);this.jc=c.gb(d)/this.ii;this.Wa=c.add(d).ua(2,!0).F(this.Cb);this.a.D.style.webkitTransform=[L.c.wc(this.Wa),L.c.Zf(this.jc,this.Cb)].join(" ");L.f.preventDefault(b)}},df:function(){if(this.sa&&this.yd){this.yd=!1;var b=this.a.z,c=Math.log(this.jc)/Math.LN2,c=this.a.cc(b+(c>0?Math.ceil(c):
Math.floor(c))),b=c-b,d=this.gh.F(this.Wa).ua(this.jc),e=this.a.aa(this.a.Ma.add(this.Cb).add(d));L.f.qa(document,"touchmove",this.ef);L.f.qa(document,"touchend",this.df);this.a.pf(e,c,Math.pow(2,b)/this.jc,this.Cb.add(d))}}});
L.t.Og=L.t.extend({enable:function(){if(!this.m)L.f.r(this.a.b,"mousewheel",this.jf,this),this.Wa=0,this.m=!0},disable:function(){if(this.m)L.f.qa(this.a.b,"mousewheel",this.jf),this.m=!1},jf:function(b){this.Wa+=L.f.Zi(b);this.zh=this.a.ig(b);clearTimeout(this.cb);this.cb=setTimeout(L.e.bind(this.Th,this),50);L.f.preventDefault(b)},Th:function(){var b=Math.round(this.Wa);this.Wa=0;if(b){var c=this.nh(this.zh,b),b=this.a.z+b;this.a.cc(b)!=this.a.z&&this.a.Ia(c,b)}},nh:function(b,c){var d=this.a.Gd().Qa(),
e=this.a.na().ua(2),e=b.F(e).V(1-Math.pow(2,-c));return this.a.aa(d.add(e),this.a.z,!0)}});L.t.Gg=L.t.extend({enable:function(){if(!this.m)this.a.n("dblclick",this.Xe,this.a),this.m=!0},disable:function(){if(this.m)this.a.fa("dblclick",this.Xe,this.a),this.m=!1},Xe:function(b){this.Ia(b.zc,this.z+1)}});
L.t.Pg=L.t.extend({l:function(b){this.a=b;this.b=b.b;this.kf=b.C.Sa},enable:function(){if(!this.m)L.f.r(this.b,"mousedown",this.Ze,this),this.m=!0},disable:function(){if(this.m)L.f.qa(this.b,"mousedown",this.Ze),this.m=!1},Ze:function(b){if(!b.shiftKey||b.which!=1&&b.button!=1)return!1;L.c.Mf();this.bb=this.a.oa(b);this.vb=L.c.create("div","leaflet-zoom-box",this.kf);L.c.W(this.vb,this.bb);this.b.style.cursor="crosshair";L.f.r(document,"mousemove",this.$e,this);L.f.r(document,"mouseup",this.af,this);
L.f.preventDefault(b)},$e:function(b){var c=this.a.oa(b),b=c.x-this.bb.x,d=c.y-this.bb.y,c=new L.j(Math.min(c.x,this.bb.x),Math.min(c.y,this.bb.y));L.c.W(this.vb,c);this.vb.style.width=Math.abs(b)-4+"px";this.vb.style.height=Math.abs(d)-4+"px"},af:function(b){this.kf.removeChild(this.vb);this.b.style.cursor="";L.c.Of();L.f.qa(document,"mousemove",this.$e);L.f.qa(document,"mouseup",this.af);b=this.a.oa(b);this.a.Pf(new L.sb(this.a.Bc(this.bb),this.a.Bc(b)))}});
L.t.fe=L.t.extend({l:function(b){this.R=b},enable:function(){if(!this.m){if(!this.H)this.H=new L.ra(this.R.Q,this.R.Q),this.H.n("dragstart",this.qd,this),this.H.n("drag",this.od,this),this.H.n("dragend",this.pd,this);this.H.enable();this.m=!0}},disable:function(){if(this.m)this.H.disable(),this.m=!1},Cc:function(){return this.H&&this.H.sa},qd:function(){this.R.Ad();this.R.h("movestart");this.R.h("dragstart")},od:function(){var b=L.c.N(this.R.Q);L.c.W(this.R.ta,b);this.R.da=this.R.a.Bc(b);this.R.h("move");
this.R.h("drag")},pd:function(){this.R.h("moveend");this.R.h("dragend")}});L.wa={};L.wa.ke={Tg:"topLeft",ak:"topRight",Sj:"bottomLeft",Bg:"bottomRight"};
L.wa.Zoom=L.p.extend({ga:function(b){this.a=b;this.b=L.c.create("div","leaflet-control-zoom");this.pi=this.Be("Zoom in","leaflet-control-zoom-in",this.a.Pj,this.a);this.qi=this.Be("Zoom out","leaflet-control-zoom-out",this.a.Qj,this.a);this.b.appendChild(this.pi);this.b.appendChild(this.qi)},Si:D("b"),N:function(){return L.wa.ke.Tg},Be:function(b,c,d,e){var f=document.createElement("a");f.href="#";f.title=b;f.className=c;L.f.Lf(f);L.f.r(f,"click",L.f.preventDefault);L.f.r(f,"click",d,e);return f}});
L.wa.Ag=L.p.extend({ga:function(b){this.b=L.c.create("div","leaflet-control-attribution");this.a=b;this.ud='Powered by <a href="http://leaflet.cloudmade.com">Leaflet</a>';this.Yb={};this.$()},N:function(){return L.wa.ke.Bg},Si:D("b"),cl:function(b){this.ud=b},ri:function(b){b&&(this.Yb[b]=!0,this.$())},tj:function(b){b&&(delete this.Yb[b],this.$())},$:function(){if(this.a){var b=[],c;for(c in this.Yb)this.Yb.hasOwnProperty(c)&&b.push(c);c=[];this.ud&&c.push(this.ud);b.length&&c.push(b.join(", "));
this.b.innerHTML=c.join(" &mdash; ")}}});
L.tb=L.p.extend({K:L.B.G,options:{Lb:L.ka.be||L.ka.Ig,scale:function(b){return 256*(1<<b)},wi:B,zoom:B,dg:[],va:!0,vg:L.k.ia&&!L.k.pc,wj:!L.k.ia,Ii:!0,Aj:!0,Oj:!0,Oa:!0,Li:L.c.ub&&!L.k.pc,Wd:L.c.ub&&!L.k.pc&&!L.k.nj,Ij:!0,Bi:!0},l:function(b,c){L.e.P(this,c);this.b=L.c.get(b);this.jd();L.f&&(this.Ya(),L.t&&this.hd(),L.wa&&this.sh());var d=this.options.wi,e=this.options.zoom;d!==B&&e!==B&&this.Ia(d,e,!0);d=this.options.dg;d=d instanceof Array?d:[d];this.mc=0;this.uh(d)},Ia:function(b,c){this.vd(b,
this.cc(c));return this},qg:function(b){return this.Ia(this.Qa(),b)},Pj:function(){return this.qg(this.z+1)},Qj:function(){return this.qg(this.z-1)},Pf:function(b){var c=this.Sf(b);return this.Ia(b.Qa(),c)},Ni:function(){var b=new L.u(-60,-170),c=new L.u(85,179);return this.Pf(new L.sb(b,c))},Uk:function(b){return this.Ia(b,this.z)},Jd:function(b){this.h("movestart");this.Wh(b);this.h("move");this.h("moveend");return this},ma:function(b){var c=L.e.nb(b);if(this.s[c])return this;this.s[c]=b;if(b.options&&
!isNaN(b.options.Ob))this.Qe=Math.max(this.Qe||0,b.options.Ob);if(b.options&&!isNaN(b.options.Pb))this.Re=Math.min(this.Re||Infinity,b.options.Pb);this.options.Wd&&L.ba&&b instanceof L.ba&&(this.mc++,b.n("load",this.cf,this));this.Oa&&b.Rf&&this.Oa.ri(b.options.qc);c=function(){b.ga(this);this.h("layeradd",{Ac:b})};this.dc?c.call(this):this.n("load",c,this);return this},mb:function(b){var c=L.e.nb(b);this.s[c]&&(b.Ga(this),delete this.s[c],this.options.Wd&&L.ba&&b instanceof L.ba&&(this.mc--,b.fa("load",
this.cf,this)),this.Oa&&b.Rf&&this.Oa.tj(b.options.qc),this.h("layerremove",{Ac:b}));return this},gj:function(){this.tf=!0;this.h("move");clearTimeout(this.hi);this.hi=setTimeout(L.e.bind(function(){this.h("moveend")},this),200);return this},Qa:function(b){var c=this.na().ua(2);return this.aa(this.ed().add(c),this.z,b)},Ek:D("z"),vk:function(){var b=this.Gd(),c=this.aa(new L.j(b.min.x,b.max.y)),b=this.aa(new L.j(b.max.x,b.min.y));return new L.sb(c,b)},Wf:function(){return isNaN(this.options.Pb)?this.Re||
0:this.options.Pb},Vf:function(){return isNaN(this.options.Ob)?this.Qe||Infinity:this.options.Ob},Sf:function(b){var c=this.na(),d=this.Wf(),e=this.Vf(),f=b.S,b=b.U,g,h;do d++,g=this.O(f,d),h=this.O(b,d),g=new L.j(g.x-h.x,h.y-g.y);while(g.x<=c.x&&g.y<=c.y&&d<=e);return d-1},na:function(){if(!this.sf||this.tf)this.sf=new L.j(this.b.clientWidth,this.b.clientHeight),this.tf=!1;return this.sf},Gd:function(){var b=this.ed(),c=this.na();return new L.Sb(b,b.add(c))},Bk:D("Ma"),Ak:D("C"),ig:function(b){return L.f.Vi(b,
this.b)},oa:function(b){return this.Bd(this.ig(b))},jg:function(b){return this.Bc(this.oa(b))},Bd:function(b){return b.F(L.c.N(this.A))},jj:function(b){return b.add(L.c.N(this.A))},Bc:function(b){return this.aa(b.add(this.Ma))},Fa:function(b){return this.O(b).ic().wf(this.Ma)},O:function(b,c){c=typeof c=="undefined"?this.z:c;return this.options.Lb.ij(b,this.options.scale(c))},aa:function(b,c,d){c=typeof c=="undefined"?this.z:c;return this.options.Lb.oj(b,this.options.scale(c),d)},jd:function(){var b=
this.b;b.className+=" leaflet-container";this.options.Li&&(b.className+=" leaflet-fade-anim");var c=L.c.Id(b,"position");if(c!="absolute"&&c!="relative")b.style.position="relative";this.vh();this.Oe&&this.Oe()},vh:function(){var b=this.C={};this.A=b.Lk=this.Aa("leaflet-map-pane",this.b);this.Eb=b.Rd=this.Aa("leaflet-tile-pane",this.A);this.Dh=b.Rk=this.Aa("leaflet-objects-pane",this.A);b.rg=this.Aa("leaflet-shadow-pane");b.Sa=this.Aa("leaflet-overlay-pane");b.fg=this.Aa("leaflet-marker-pane");b.mg=
this.Aa("leaflet-popup-pane")},Aa:function(b,c){return L.c.create("div",b,c||this.Dh)},vd:function(b,c,d){var e=this.z!=c;this.h("movestart");this.z=c;this.Ma=this.Le(b);d?this.Ma.re(L.c.N(this.A)):L.c.W(this.A,new L.j(0,0));this.xf=this.mc;this.h("viewreset");this.h("move");e&&this.h("zoomend");this.h("moveend");if(!this.dc)this.dc=!0,this.h("load")},uh:function(b){this.s={};for(var c=0,d=b.length;c<d;c++)this.ma(b[c])},sh:function(){this.options.Oj&&this.Gf(new L.wa.Zoom);if(this.options.Oa)this.Oa=
new L.wa.Ag,this.Gf(this.Oa)},Wh:function(b){L.c.W(this.A,L.c.N(this.A).F(b))},Ya:function(){L.f.r(this.b,"click",this.zb,this);for(var b=["dblclick","mousedown","mouseenter","mouseleave","mousemove"],c=0;c<b.length;c++)L.f.r(this.b,b[c],this.La,this);this.options.Ij&&L.f.r(window,"resize",this.gj,this)},zb:function(b){if(!this.va||!this.va.Cc())this.h("pre"+b.type),this.La(b)},La:function(b){var c=b.type,c=c=="mouseenter"?"mouseover":c=="mouseleave"?"mouseout":c;this.xc(c)&&this.h(c,{zc:this.jg(b),
cg:this.oa(b)})},hd:function(){var b={va:L.t.Lg,vg:L.t.Wg,Ii:L.t.Gg,wj:L.t.Og,Aj:L.t.Pg},c;for(c in b)b.hasOwnProperty(c)&&b[c]&&(this[c]=new b[c](this),this.options[c]&&this[c].enable())},cf:function(){this.xf--;if(this.mc&&!this.xf&&this.D)clearTimeout(this.jh),this.jh=setTimeout(L.e.bind(this.ih,this),500)},ed:function(){if(!this.dc)throw Error("Set map center and zoom first.");return this.Ma.F(L.c.N(this.A))},Le:function(b){var c=this.na().ua(2);return this.O(b).F(c).round()},cc:function(b){return Math.max(this.Wf(),
Math.min(this.Vf(),b))}});
L.tb.ea({mj:function(b){var c={timeout:1E4};L.e.extend(c,b);navigator.geolocation?navigator.geolocation.getCurrentPosition(L.e.bind(this.rh,this),L.e.bind(this.qh,this),c):this.h("locationerror",{code:0,message:"Geolocation not supported."});return this},Kk:function(b,c){this.kc=!0;this.Ch=b||Infinity;return this.mj(c)},qh:function(b){var b=b.code,c=b==1?"permission denied":b==2?"position unavailable":"timeout";if(this.kc)this.Ni(),this.kc=!1;this.h("locationerror",{code:b,message:"Geolocation error: "+
c+"."})},rh:function(b){var c=180*b.coords.accuracy/4E7,d=c*2,e=b.coords.latitude,f=b.coords.longitude,g=new L.u(e-c,f-d),c=new L.u(e+c,f+d),g=new L.sb(g,c);if(this.kc)c=Math.min(this.Sf(g),this.Ch),this.Ia(g.Qa(),c),this.kc=!1;this.h("locationfound",{zc:new L.u(e,f),nk:g,accuracy:b.coords.accuracy})}});L.tb.ea({Ec:function(b){this.Ad();this.M=b;return this.ma(b)},Ad:function(){this.M&&this.mb(this.M);return this}});
L.tb.ea(!L.o||!L.o.ej()?{}:{Ia:function(b,c,d){var c=this.cc(c),e=this.z!=c;if(this.dc&&!d&&this.s&&(d=this.Le(b).F(this.ed()),e?this.Ff&&this.Ff(b,c,d):this.Sh(d)))return this;this.vd(b,c);return this},Jd:function(b){if(!this.gc)this.gc=new L.o(this.A,{duration:0.3}),this.gc.n("step",this.Jh,this),this.gc.n("end",this.Ih,this);this.h(this,"movestart");this.gc.Nd({position:L.c.N(this.A).F(b)});return this},Jh:function(){this.h("move")},Ih:function(){this.h("moveend")},Sh:function(b){if(this.We(b))return this.Jd(b),
!0;return!1},We:function(b,c){var d=c||1,e=this.na();return Math.abs(b.x)<=e.x*d&&Math.abs(b.y)<=e.y*d}});
L.tb.ea(!L.c.ub?{}:{Ff:function(b,c,d){if(this.Xb)return!0;if(!this.options.Wd)return!1;var e=Math.pow(2,c-this.z),d=d.ua(1-1/e);if(!this.We(d,1))return!1;this.A.className+=" leaflet-zoom-anim";d=this.Bd(this.na().ua(2)).add(d);this.mf();this.pf(b,c,e,d);return!0},pf:function(b,c,d,e){this.Xb=!0;this.bh=b;this.dh=c;b=L.c.Wb;if(L.k.Qi||window.opera)this.D.style[b]+=" translate(0,0)";L.k.pc?(this.D.style[b+"Origin"]=e.x+"px "+e.y+"px",d="scale("+d+")"):d=L.c.Zf(d,e);e={};e[b]=this.D.style[b]+" "+d;
this.D.Sd.Nd(e)},mf:function(){if(!this.D)this.D=this.Aa("leaflet-tile-pane",this.A),this.D.style.zIndex=1;var b=this.Eb,c=this.D;c.style[L.c.Wb]="";c.style.visibility="hidden";c.empty=!0;b.empty=!1;this.Eb=this.C.Rd=c;this.D=b;if(!this.D.Sd)this.D.Sd=new L.o(this.D,{duration:0.3,Ed:"cubic-bezier(0.25,0.1,0.25,0.75)"}),this.D.Sd.n("end",this.Kh,this);this.li()},li:function(){for(var b=[].slice.call(this.D.getElementsByTagName("img")),c=0,d=b.length;c<d;c++)if(!b[c].complete)b[c].src="",b[c].parentNode.removeChild(b[c])},
Kh:function(){this.ci();this.vd(this.bh,this.dh,!0);this.A.className=this.A.className.replace(" leaflet-zoom-anim","");this.Xb=!1},ci:function(){this.Eb.innerHTML="";this.Eb.style.visibility="";this.Eb.style.zIndex=2;this.D.style.zIndex=1},ih:function(){if(!this.Xb&&!this.vg.yd)this.D.innerHTML=""}});
L.tb.ea({Gf:function(b){b.ga(this);var c=b.N(),d=this.Ae[c],b=b.b;L.c.si(b,"leaflet-control");c.indexOf("bottom")!=-1?d.insertBefore(b,d.firstChild):d.appendChild(b);return this},Wk:function(b){this.Ae[b.N()].removeChild(b.b);b.Ga&&b.Ga(this);return this},Oe:function(){var b=this.Ae={},c=L.c.create("div","leaflet-control-container",this.b);L.k.ia&&(c.className+=" leaflet-big-buttons");b.il=L.c.create("div","leaflet-top leaflet-left",c);b.jl=L.c.create("div","leaflet-top leaflet-right",c);b.lk=L.c.create("div",
"leaflet-bottom leaflet-left",c);b.mk=L.c.create("div","leaflet-bottom leaflet-right",c)}});L.ba.Yj=L.ba.Ja.extend({options:{Ta:1024,zg:2,Pb:2,Ob:22,Ud:!0,wg:!0,qc:'Map data &copy; 2011 OpenStreetMap contributors, Rendering by <a href="http://github.com/kothic/kothic-js">Kothic JS</a>',async:!0,buffered:!1},l:function(b){L.e.P(this,b);this.Wc={};this.Ge=[];this.options.ob=b.ob||Q;window.Sk=L.e.bind(this.Hh,this);this.hj=new Kothic({buffered:this.options.buffered,ob:this.options.ob,lj:["be","ru","en"]})},Hh:function(b,c,d,e){var f=[c,d,e].join("/"),g=this.Wc[f],h=this.options.zg,j=this;this.xh(b);
this.hj.ha(g,b,c+h,function(b){j.Ge.push(j.Ui(b,d,e,c));j.tg(g)});delete this.Wc[f]},Ui:function(b,c,d,e){c="<b>tile "+c+":"+d+":"+e+"</b><br />";c+="<table>";for(var f in b.Hc)b.Hc.hasOwnProperty(f)&&(c+="<tr><td>"+b.Hc[f]+"</td><td>"+f+"</td></tr>");c+="</table><table>";d=f=b.hb[0].timestamp;for(e=1;e<b.hb.length;e++)c+="<tr><td>"+(b.hb[e].timestamp-f)+"&nbsp;ms</td><td>"+b.hb[e].message+"</td></tr>",f=b.hb[e].timestamp;c+="<tr><td>"+(f-d)+"&nbsp;ms</td><td>total</td></tr>";c+="</table>";return c},
wk:D("Ge"),Nf:function(b,c,d){c=[d-this.options.zg,c.x,c.y].join("/");this.Wc[c]=b;this.Bh("http://osmosnimki.ru/vtile/"+c+".js")},xh:function(b){var c,d,e=b.$i,f,g,h,j;for(f=0;f<b.ib.length;f++){j=b.ib[f];d=j.Da;c=b.ib[f].type;if(c=="Point")d[1]=e-d[1];else if(c=="MultiPoint"||c=="LineString")for(c=0;c<d.length;c++)d[c][1]=e-d[c][1];else if(c=="MultiLineString"||c=="Polygon")for(g=0;g<d.length;g++)for(c=0;c<d[g].length;c++)d[g][c][1]=e-d[g][c][1];else if(c=="MultiPolygon")for(h=0;h<d.length;h++)for(g=
0;g<d[h].length;g++)for(c=0;c<d[h][g].length;c++)d[h][g][c][1]=e-d[h][g][c][1];else window.console&&window.console.log("Unexpected GeoJSON type: "+c);"reprpoint"in j&&(j.Md[1]=e-j.Md[1])}},Bh:function(b){var c=document.createElement("script");c.src=b;c.charset="utf-8";document.getElementsByTagName("head")[0].appendChild(c)}});/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
K={};K.ya={P:function(b,c){b.options=K.ya.extend({},b.options,c)},extend:function(b){var c=Array.prototype.slice.call(arguments,1),d=c.length,e,f,g;for(f=0;f<d;f++)for(e in g=c[f]||{},g)g.hasOwnProperty(e)&&(b[e]=g[e]);return b},Ik:function(b){for(var c in b)if(b.hasOwnProperty(c))return!1;return!0}};K.p=C();
K.p.extend=function(b){function c(){}function d(){this.l&&this.l.apply(this,arguments)}c.prototype=this.prototype;var e=new c;e.constructor=d;d.prototype=e;d.Fj=this.prototype;for(var f in this)this.hasOwnProperty(f)&&f!="prototype"&&f!="superclass"&&(d[f]=this[f]);b.Y&&(K.ya.extend(d,b.Y),delete b.Y);b.K&&(K.ya.extend.apply(B,[e].concat(b.K)),delete b.K);if(b.options&&e.options)b.options=K.ya.extend({},e.options,b.options);K.ya.extend(e,b);d.extend=arguments.callee;d.ea=function(b){K.ya.extend(this.prototype,b)};
return d};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic=K.p.extend({options:{buffered:!1,Kc:!1,ob:[],lj:[]},l:function(b){K.ya.P(this,b)},ha:function(b,c,d,e){function f(){r.$h(t,s,q,n,p,o);m.oc("labels rendered");g.Ci();m.oc("buffer was copied");e(m)}var g=new Kothic.Ja(b,{ok:this.options.buffered,Kc:this.options.Kc}),h=g.width,j=g.height,l=c.$i,n=h/l,p=j/l,q=g.sc,k=this.options.ob,o=new Kothic.Zd(j,h),m=new Kothic.Fg,s=this.Uh(c.ib,d,k),t=Kothic.ja.Xf(s);m.oc("layers styled: "+R+"/"+S);R=S=0;Kothic.style.X(q,Kothic.style.Gi);var r=this;setTimeout(function(){r.Yh(q,
h,j,d,k);var b=r.Zh(t,s,q,n,p,l);m.oc("geometry rendered");m.yj(b);setTimeout(f,0)},0)},Uh:function(b,c,d){for(var e={},d=Kothic.style.Ej(b,c,d),b=0,c=d.length;b<c;b++){var f=d[b],g=parseFloat(f.Ld.Ac)||0,h=f.style["-x-mapnik-layer"];h==="top"&&(g=1E4);h==="bottom"&&(g=-1E4);e.hasOwnProperty(g)||(e[g]=[]);e[g].push(f)}return e},Yh:function(b,c,d,e,f){function g(){b.fillRect(-1,-1,c+1,d+1)}var e=T(f,{},{},e,"canvas"),f=Kothic.ja.Xf(e),h;for(h=0;h<f.length;h++)Kothic.lg.fill(b,e[f[h]],g)},Zh:function(b,
c,d,e,f,g){var h=0,j=0,l=0,n,p;for(p=0;p<b.length;p++){var q=c[b[p]],k=q.length;for(n=0;n<k;n++){var o=q[n].style;if(o.hasOwnProperty("fill-color")||o.hasOwnProperty("fill-image"))Kothic.lg.ha(d,q[n],q[n+1],e,f,g),h+=1}d.lineCap="butt";for(n=0;n<k;n++)q[n].style.hasOwnProperty("casing-width")&&(Kothic.eg.uj(d,q[n],q[n+1],e,f,g),l+=1);d.lineCap="round";for(n=0;n<k;n++)q[n].style.width&&(Kothic.eg.ha(d,q[n],q[n+1],e,f,g),j+=1)}return{"polygons rendered ":h,"lines rendered ":j,"casings rendered ":l}},
$h:function(b,c,d,e,f,g){var h=d.strokeText&&d.fillText&&d.measureText,j=0,l=0,n=0,p,q,k;for(k=0;k<b.length;k++){var o=c[b[k]],m=o.length;for(p=m-1;p>=0;p--)q=o[p].style,q.hasOwnProperty("icon-image")&&!q.text&&(Kothic.Qd.ha(d,o[p],g,e,f,!1,!0),j+=1);for(p=m-1;h&&p>=0;p--)q=o[p].style,!q.hasOwnProperty("icon-image")&&q.text&&(Kothic.Qd.ha(d,o[p],g,e,f,!0,!1),l+=1);for(p=m-1;p>=0;p--)q=o[p].style,q.hasOwnProperty("icon-image")&&q.text&&(Kothic.Qd.ha(d,o[p],g,e,f,h,!0),j+=1,l+=1);for(p=m-1;h&&p>=0;p--)q=
o[p].style,q["shield-text"]&&(Kothic.zj.ha(d,o[p],g,e,f),n+=1)}return{"icons rendered ":j,"labels rendered ":l,"shields rendered ":n}}});/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.Ja=K.p.extend({options:{buffered:!1,Kc:!1},l:function(b,c){K.ya.P(this,c);this.canvas=typeof b==="string"?document.getElementById(b):b;this.width=b.width;this.height=b.height;this.options.buffered?(this.buffer=Kothic.Ja.zd.length>0?Kothic.Ja.zd.pop():document.createElement("canvas"),this.buffer.width=b.width,this.buffer.height=b.height,this.sc=this.buffer.getContext("2d")):this.sc=this.canvas.getContext("2d");if(c.Kc)this.sc=new CanvasProxy(this.sc)},Ci:function(){this.options.buffered&&(this.canvas.getContext("2d").drawImage(this.buffer,
0,0),Kothic.Ja.zd.push(this.buffer))}});Kothic.Ja.zd=[];/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
CanvasProxy=function(b){var c={strokeStyle:"rgba(0,0,0,0.5)",fillStyle:"rgba(0,0,0,0.5)",lineWidth:1,globalAlpha:1,lineCap:"round",lineJoin:"round",textAlign:"center",textBaseline:"middle"};_textMeasureCache={};for(var d in this.ck)c.hasOwnProperty(d)&&(this[d]=c[d],b[d]=c[d]);this.jk="default";this.ve=function(){var d=["globalAlpha","strokeStyle","lineWidth","lineCap","lineJoin"],f;for(f in d)f=d[f],this[f]!=c[f]&&this[f]&&(b[f]=this[f],c[f]=this[f])};this.Xc=function(){var d=["globalAlpha","fillStyle"],
f;for(f in d)f=d[f],this[f]!=c[f]&&this[f]&&(b[f]=this[f],c[f]=this[f])};this.Zc=function(){var d=["font","textAlign","textBaseline"],f;for(f in d)f=d[f],this[f]!=c[f]&&this[f]&&(b[f]=this[f],c[f]=this[f])};this.ai=function(){var c=["fillStyle","strokeStyle","lineCap","textAlign","textBaseline","globalAlpha"],d;for(d in c)d=c[d],this[d]&&(b[d]=this[d])};this.fillRect=function(c,d,g,h){this.Xc();b.fillRect(c,d,g,h)};this.drawImage=function(c,d,g){b.drawImage(c,d,g)};this.lineTo=function(c,d){b.lineTo(c,
d)};this.moveTo=function(c,d){b.moveTo(c,d)};this.translate=function(c,d){b.translate(c,d)};this.createPattern=function(c,d){b.createPattern(c,d)};this.rotate=function(c){b.rotate(c)};this.save=function(){b.save()};this.restore=function(){b.restore();this.ai()};this.beginPath=function(){b.beginPath()};this.stroke=function(){this.ve();b.stroke()};this.fill=function(){this.Xc();b.fill()};this.fillText=function(c,d,g){this.Xc();this.Zc();b.fillText(c,d,g)};this.strokeText=function(c,d,g){this.ve();this.Zc();
b.strokeText(c,d,g)};this.measureText=function(c){this.Zc();var d=this.font;_textMeasureCache[d]||(_textMeasureCache[d]={});_textMeasureCache[d][c]||(_textMeasureCache[d][c]=b.measureText(c));return _textMeasureCache[d][c]}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.path=function(){function b(b,c){e={pattern:c,Fc:0,Kd:0,x:b[0],y:b[1]}}function c(b,c){var d=e,j=c[0]-d.x,l=c[1]-d.y,n=Math.sqrt(j*j+l*l),p;b.save();b.translate(d.x,d.y);b.rotate(Math.atan2(l,j));b.moveTo(0,0);j=0;do{p=d.pattern[d.Fc];j+=p-d.Kd;l=j<n;if(!l)d.Kd=p-(j-n),j=n;b[d.Fc%2?"moveTo":"lineTo"](j,0);if(l)d.Kd=0,d.Fc=++d.Fc%d.pattern.length}while(l);d.x=c[0];d.y=c[1];b.restore()}function d(b,c){return b[0]===0||b[0]===c||b[1]===0||b[1]===c}var e;return function(e,g,h,j,l,n,p){var q=g.type,
g=g.Da;q==="Polygon"&&(g=[g],q="MultiPolygon");q==="LineString"&&(g=[g],q="MultiLineString");var k,o,m,s,t=g.length,r,v,w,x,u;if(q==="MultiPolygon")for(k=0;k<t;k++){m=0;for(r=g[k].length;m<r;m++){s=g[k][m];v=s.length;w=s[0];for(o=0;o<=v;o++)x=s[o]||s[0],u=Kothic.ja.pb(x,l,n),o===0||!j&&d(x,p)&&d(w,p)?(w=h,e.moveTo(u[0],u[1]),w&&b(u,w)):j||!h?e.lineTo(u[0],u[1]):c(e,u),w=x}}if(q==="MultiLineString")for(k=0;k<t;k++){s=g[k];v=s.length;for(o=0;o<v;o++){x=s[o];u=Kothic.ja.pb(x,l,n);if((o===0||o===v-1)&&
d(x,p))w=s[o?v-2:1],j=x[0]-w[0],q=x[1]-w[1],x=Math.sqrt(j*j+q*q),u=[u[0]+50*j/x,u[1]+50*q/x];o===0?(j=u,q=h,e.moveTo(j[0],j[1]),q&&b(j,q)):h?c(e,u):e.lineTo(u[0],u[1])}}}}();/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.eg={pa:!1,uj:function(b,c,d,e,f,g){var h=c.style,j=d&&d.style,l=h["casing-dashes"]||h.Dd||!1;if(!this.pa)this.pa=!0,b.beginPath();Kothic.path(b,c,l,!1,e,f,g);if(!d||!(j.width===h.width&&j["casing-width"]===h["casing-width"]&&j["casing-color"]===h["casing-color"]&&(j["casing-dashes"]||j.Dd||!1)===(h["casing-dashes"]||h.Dd||!1)&&(j["casing-linecap"]||j.jb||"butt")===(h["casing-linecap"]||h.jb||"butt")&&(j["casing-linejoin"]||j.kb||"round")===(h["casing-linejoin"]||h.kb||"round")&&(j["casing-opacity"]||
j.opacity)===(h.opacity||h["casing-opacity"])))Kothic.style.X(b,{lineWidth:2*h["casing-width"]+(h.hasOwnProperty("width")?h.width:0),strokeStyle:h["casing-color"]||"#000000",lineCap:h["casing-linecap"]||h.jb||"butt",lineJoin:h["casing-linejoin"]||h.kb||"round",globalAlpha:h["casing-opacity"]||1}),this.pa=!1,b.stroke()},ha:function(b,c,d,e,f,g){var h=c.style,j=d&&d.style,l=h.Dd;if(!this.pa)this.pa=!0,b.beginPath();Kothic.path(b,c,l,!1,e,f,g);if(!d||!((j.width||1)===(h.width||1)&&(j.color||"#000000")===
(h.color||"#000000")&&j.jb===h.jb&&j.kb===h.kb&&j.bg===h.bg&&j.opacity===h.opacity)){if(h.hasOwnProperty("color")||!h.hasOwnProperty("image"))Kothic.style.X(b,{lineWidth:h.width||1,strokeStyle:h.color||"#000000",lineCap:h.jb||"round",lineJoin:h.kb||"round",globalAlpha:h.opacity||1}),b.stroke();if(h.hasOwnProperty("image")&&(c=U(h.bg)))Kothic.style.X(b,{strokeStyle:b.createPattern(c,"repeat")||"#000000",lineWidth:h.width||1,lineCap:h.jb||"round",lineJoin:h.kb||"round",globalAlpha:h.opacity||1}),b.stroke();
this.pa=!1}}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.lg={pa:!1,ha:function(b,c,d,e,f,g){var h=c.style,j=d&&d.style;if(!this.pa)this.pa=!0,b.beginPath();Kothic.path(b,c,!1,!0,e,f,g);if(!d||!(j["fill-color"]===h["fill-color"]&&j["fill-image"]===h["fill-image"]&&j["fill-opacity"]===h["fill-opacity"]))this.fill(b,h,function(){b.fill()}),this.pa=!1},fill:function(b,c,d){var e=c["fill-opacity"]||c.opacity;c.hasOwnProperty("fill-color")&&(Kothic.style.X(b,{fillStyle:c["fill-color"]||"#000000",globalAlpha:e||1}),d());if(c.hasOwnProperty("fill-image")&&
(c=U(c["fill-image"])))Kothic.style.X(b,{fillStyle:b.createPattern(c,"repeat"),globalAlpha:e||1}),d()}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.zj={ha:function(b,c,d,e,f){var g=c.style,h=Kothic.ja.Yf(c),j,l,n=0,p=!1,q,k;if(h){j=Kothic.ja.pb(h,e,f);if(g["shield-image"]&&(l=U(g["icon-image"]),!l))return;Kothic.style.X(b,{font:Kothic.style.Uf(g["shield-font-family"]||g["font-family"],g["shield-font-size"]||g["font-size"]),fillStyle:g["shield-text-color"]||"#000000",globalAlpha:g["shield-text-opacity"]||g.opacity||1,textAlign:"center",textBaseline:"middle"});var o=String(g["shield-text"]),h=b.measureText(o).width,m=h+2,s=h/o.length*1.8;
if(c.type==="LineString"){n=Kothic.Pa.Hd(c.Da);if(Math.max(s/f,m/e)>n)return;q=0;for(k=1;q<n/2;q+=Math.max(n/30,s/e),k*=-1){h=Kothic.Pa.uc(c.Da,n/2+k*q,0);if(!h)break;h=[h[1],h[2]];j=Kothic.ja.pb(h,e,f);if((!l||!(g["allow-overlap"]!=="true"&&d.Ib(j,l.width,l.height,c.Ea)))&&!(g["allow-overlap"]!=="true"&&d.Ib(j,m,s,c.Ea))){p=!0;break}}}p&&(g["shield-casing-width"]&&(Kothic.style.X(b,{fillStyle:g["shield-casing-color"]||"#000000",globalAlpha:g["shield-casing-opacity"]||g.opacity||1}),b.fillRect(j[0]-
m/2-(g["shield-casing-width"]||0)-(g["shield-frame-width"]||0),j[1]-s/2-(g["shield-casing-width"]||0)-(g["shield-frame-width"]||0),m+2*(g["shield-casing-width"]||0)+2*(g["shield-frame-width"]||0),s+2*(g["shield-casing-width"]||0)+2*(g["shield-frame-width"]||0))),g["shield-frame-width"]&&(Kothic.style.X(b,{fillStyle:g["shield-frame-color"]||"#000000",globalAlpha:g["shield-frame-opacity"]||g.opacity||1}),b.fillRect(j[0]-m/2-(g["shield-frame-width"]||0),j[1]-s/2-(g["shield-frame-width"]||0),m+2*(g["shield-frame-width"]||
0),s+2*(g["shield-frame-width"]||0))),g["shield-color"]&&(Kothic.style.X(b,{fillStyle:g["shield-color"]||"#000000",globalAlpha:g["shield-opacity"]||g.opacity||1}),b.fillRect(j[0]-m/2,j[1]-s/2,m,s)),l&&b.drawImage(l,Math.floor(j[0]-l.width/2),Math.floor(j[1]-l.height/2)),Kothic.style.X(b,{fillStyle:g["shield-text-color"]||"#000000",globalAlpha:g["shield-text-opacity"]||g.opacity||1}),b.fillText(o,j[0],Math.ceil(j[1])),l&&d.Hb(j,l.width,l.height,0,c.Ea),d.Hb(j,s,m,(parseFloat(g["shield-casing-width"])||
0)+(parseFloat(g["shield-frame-width"])||0)+(parseFloat(g["-x-mapnik-min-distance"])||30),c.Ea))}}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.Gj=function(){function b(b,c){return[b[1]+0.5*Math.cos(b[0])*c,b[2]+0.5*Math.sin(b[0])*c]}function c(c,d,e,j){var j=j||0,l=c.measureText(d).width,c=c.measureText(d.charAt(0)).width*1.5,d=e[0];return[b(e,l+2*j),Math.abs(Math.cos(d)*l)+Math.abs(Math.sin(d)*c),Math.abs(Math.sin(d)*l)+Math.abs(Math.cos(d)*c),0]}function d(b,d,e,j){var l,n=0;for(l=0;l<=e.length;l++){if(b.Ib.apply(b,c(d,e.charAt(l),j,n)))return!0;n+=d.measureText(e.charAt(l)).width}return!1}function e(c,d,e){var j=d[4],l=b(d,c.measureText(j).width);
c.translate(l[0],l[1]);c.rotate(d[0]);c[e?"strokeText":"fillText"](j,0,0);c.rotate(-d[0]);c.translate(-l[0],-l[1])}return function(b,g,h,j,l){var n=b.measureText(h).width,p=h.length,q=Kothic.Pa.Hd(g);if(!(q<n)){for(var k,o,m,s,t=0,r,v=!1,w,x,u,z=Math.PI/6;t<2;){o=t?b.measureText(h.charAt(0)).width:(q-n)/2;r=0;m=B;s=[];for(u=0;u<p;u++){k=h.charAt(u);x=b.measureText(k).width;w=Kothic.Pa.uc(g,o,x);if(o>=q||!w){t++;s=[];v&&(g.reverse(),v=!1);break}m||(m=w[0]);if(d(l,b,k,w)||Math.abs(m-w[0])>z)o+=x,u=
-1,s=[],r=0;else{for(;x<w[3]&&u<p;){u++;k+=h.charAt(u);x=b.measureText(k).width;if(d(l,b,k,w)){u=0;o+=x;s=[];r=0;k=h.charAt(u);x=b.measureText(k).width;w=Kothic.Pa.uc(g,o,x);break}if(x>=w[3]){u--;k=k.slice(0,-1);x=b.measureText(k).width;break}}if(w){if(w[0]>Math.PI/2||w[0]<-Math.PI/2)r+=k.length;m=w[0];w.push(k);s.push(w);o+=x}}}r>p/2&&(g.reverse(),s=[],v?(t++,g.reverse(),v=!1):v=!0);if(t>=2)return;if(s.length>0)break}g=s.length;for(u=0;j&&u<g;u++)e(b,s[u],!0);for(u=0;u<g;u++){w=s[u];e(b,w);j=l;h=
b;n=w[4];p=y;for(p=q=0;p<=n.length;p++)j.Hb.apply(j,c(h,n.charAt(p),w,q)),q+=h.measureText(n.charAt(p)).width}}}}();/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.Qd={ha:function(b,c,d,e,f,g,h){var j=c.style,l,n;if(h||g&&c.type!=="LineString"){n=Kothic.ja.Yf(c);if(!n)return;n=Kothic.ja.pb(n,e,f)}if(h){l=U(j["icon-image"]);if(!l)return;if(j["allow-overlap"]!=="true"&&d.Ib(n,l.width,l.height,c.Ea))return}if(g){Kothic.style.X(b,{lineWidth:j["text-halo-radius"]*2,font:Kothic.style.Uf(j["font-family"],j["font-size"])});var g=String(j.text),p=b.measureText(g).width,q=p/g.length*2.5,k=j["text-offset"]||0,o=j.hasOwnProperty("text-halo-radius");Kothic.style.X(b,
{fillStyle:j["text-color"]||"#000000",strokeStyle:j["text-halo-color"]||"#ffffff",globalAlpha:j["text-opacity"]||j.opacity||1,textAlign:"center",textBaseline:"middle"});if(c.type==="Polygon"||c.type==="Point"){if(j["text-allow-overlap"]!=="true"&&d.Ib([n[0],n[1]+k],p,q,c.Ea))return;o&&b.strokeText(g,n[0],n[1]+k);b.fillText(g,n[0],n[1]+k);d.Hb([n[0],n[1]+k],p,q,j["-x-mapnik-min-distance"]||20,c.Ea)}else c.type==="LineString"&&(e=Kothic.ja.Jj(c.Da,e,f),Kothic.Gj(b,e,g,o,d))}h&&(b.drawImage(l,Math.floor(n[0]-
l.width/2),Math.floor(n[1]-l.height/2)),d.Hb(n,l.width,l.height,parseFloat(j["-x-mapnik-min-distance"])||0,c.Ea))}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
var V={},Q=[],W={},R=0,S=0;function U(b){var c=W[b];if(c.Dj){var d=document.createElement("canvas");d.width=c.width;d.height=c.height;d.getContext("2d").drawImage(c.Dj,0,c.Dc,c.width,c.height,0,0,c.width,c.height);c=W[b]=d}return c}function T(b,c,d,e,f){var g,h=this.Dk(c,d,e,f),j=this.Jf[h]||{};if(this.Jf.hasOwnProperty(h))this.Fi.Gk+=1;else{this.Fi.Mk+=1;for(g=0;g<b.length;g++)j=V[b[g]].Zk(j,c,d,e,f);this.Jf[h]=j}return j};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.style={Gi:{strokeStyle:"rgba(0,0,0,0.5)",fillStyle:"rgba(0,0,0,0.5)",lineWidth:1,lineCap:"round",lineJoin:"round",textAlign:"center",textBaseline:"middle"},Id:function(b,c,d){var e,f;if(b.type==="Polygon"||b.type==="MultiPolygon")e="way",f="area";else if(b.type==="LineString"||b.type==="MultiLineString")e="way",f="line";else if(b.type==="Point"||b.type==="MultiPoint")f=e="node";return T(d,b.Ld,c,e,f)},Ej:function(b,c,d){var e=[],f,g,h,j,l,n;f=0;for(h=b.length;f<h;f++)for(g in j=b[f],l=this.Id(j,
c,d),l)if(l.hasOwnProperty(g))n=Kothic.ja.extend({},j),n.Ea=f+1,n.style=l[g],e.push(n);e.sort(function(b,c){return parseFloat(b.style["z-index"])-parseFloat(c.style["z-index"]||0)});return e},Uf:function(b,c){var b=b||"",c=c||9,d=b?b+", ":"",b=b.toLowerCase(),e=[];(b.indexOf("italic")!==-1||b.indexOf("oblique")!==-1)&&e.push("italic");b.indexOf("bold")!==-1&&(e.push("bold"),d+=b.replace("bold","")+", ");e.push(c+"px");d+=b.indexOf("serif")!==-1?"Georgia, serif":'"Helvetica Neue", Arial, Helvetica, sans-serif';
e.push(d);return e.join(" ")},X:function(b,c){for(var d in c)c.hasOwnProperty(d)&&(b[d]=c[d])}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
(function(b){b.Zd=function(b,d){this.buffer=new aa;this.height=b;this.width=d};b.Zd.prototype={Hb:function(b,d,e,f,g){this.buffer.fj(this.Tf(b,d,e,f),g)},xi:function(b,d){if(this.height&&!(b.Mj>=0&&b.Nj>=0&&b.rb<=this.height&&b.Va<=this.width))return!0;var e=[];this.buffer.search(b,!0,e);var f,g,h;f=0;for(g=e.length;f<g;f++)if(h=e[f],d!==h.Ra)return!0;return!1},Ib:function(b,d,e,f){return this.xi(this.Tf(b,d,e,0),f)},Tf:function(b,d,e,f){return new ba(b[0]-d/2-f,b[1]-e/2-f,d+2*f,e+2*f)}}})(Kothic);/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.Pa={Hd:function(b){var c=b.length,d,e,f,g,h=0;for(f=1;f<c;f++)d=b[f],e=b[f-1],g=e[0]-d[0],d=e[1]-d[1],h+=Math.sqrt(g*g+d*d);return h},uc:function(b,c,d){var e=b.length,f,g,h,j,l,n,p,q=0;n=0;var k,o=!0;k=!1;d=d||0;for(l=1;l<e;l++){k&&(o=!1);n=b[l];p=b[l-1];f=n[0]-p[0];g=n[1]-p[1];n=Math.sqrt(f*f+g*g);!k&&q+n>=c&&(k=c-q,h=p[0]+f*k/n,j=p[1]+g*k/n,k=!0);if(k&&q+n>=c+d)return k=c+d-q,f=p[0]+f*k/n,g=p[1]+g*k/n,b=Math.atan2(g-j,f-h),o?[b,h,j,n-k]:[b,h,j,0];q+=n}}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.ja={pb:function(b,c,d){return[c*b[0],d*b[1]]},Jj:function(b,c,d){var e=[],f;f=0;for(len=b.length;f<len;f++)e.push(this.pb(b[f],c,d));return e},Yf:function(b){var c;switch(b.type){case "Point":c=b.Da;break;case "Polygon":c=b.Md;break;case "LineString":c=Kothic.Pa.Hd(b.Da);c=Kothic.Pa.uc(b.Da,c/2,0);c=[c[1],c[2]];break;case "GeometryCollection":return;case "MultiPoint":return;case "MultiPolygon":c=b.Md;break;case "MultiLineString":return}return c},Xf:function(b){var c=[],d;for(d in b)b.hasOwnProperty(d)&&
c.push(d);c.sort();return c},extend:function(b,c){for(var d in c)c.hasOwnProperty(d)&&(b[d]=c[d]);return b}};/*
 Copyright (c) 2009 Jon-Carlos Rivera

 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 Jon-Carlos Rivera - imbcmdth@hotmail.com
*/
function aa(){function b(b,c){var d;if(c.d.length==0)c.x=b.x,c.y=b.y,c.g=b.g,c.i=b.i,c.d.push(b);else{var g=-1,h=[],k;h.push(c);var o=c.d;do{if(g!=-1)h.push(o[g]),o=o[g].d,g=-1;for(var m=o.length-1;m>=0;m--){var s=o[m];if("leaf"in s){g=-1;break}var t=X(s.g,s.i,s.d.length+1),s=X(Math.max(s.x+s.g,b.x+b.g)-Math.min(s.x,b.x),Math.max(s.y+s.i,b.y+b.i)-Math.min(s.y,b.y),s.d.length+2);if(g<0||Math.abs(s-t)<k)k=Math.abs(s-t),g=m}}while(g!=-1);g=b;do{if(d&&"nodes"in d&&d.d.length==0){k=d;d=h.pop();for(o=0;o<
d.d.length;o++)if(d.d[o]===k||d.d[o].d.length==0){d.d.splice(o,1);break}}else d=h.pop();if("leaf"in g||"nodes"in g||Object.prototype.toString.call(g)==="[object Array]"){if(Object.prototype.toString.call(g)==="[object Array]"){for(k=0;k<g.length;k++)Y(d,g[k]);d.d=d.d.concat(g)}else Y(d,g),d.d.push(g);if(d.d.length<=f)g={x:d.x,y:d.y,g:d.g,i:d.i};else{k=g=d.d;for(var o=k.length-1,m=0,t=k.length-1,s=0,r=y,v=y,r=k.length-2;r>=0;r--)v=k[r],v.x>k[m].x?m=r:v.x+v.g<k[o].x+k[o].g&&(o=r),v.y>k[s].y?s=r:v.y+
v.i<k[t].y+k[t].i&&(t=r);Math.abs(k[o].x+k[o].g-k[m].x)>Math.abs(k[t].y+k[t].i-k[s].y)?o>m?(r=k.splice(o,1)[0],v=k.splice(m,1)[0]):(v=k.splice(m,1)[0],r=k.splice(o,1)[0]):t>s?(r=k.splice(t,1)[0],v=k.splice(s,1)[0]):(v=k.splice(s,1)[0],r=k.splice(t,1)[0]);for(k=[{x:r.x,y:r.y,g:r.g,i:r.i,d:[r]},{x:v.x,y:v.y,g:v.g,i:v.i,d:[v]}];g.length>0;){for(var o=g,m=k[0],t=k[1],r=X(m.g,m.i,m.d.length+1),v=X(t.g,t.i,t.d.length+1),w=y,x=y,s=y,u=o.length-1;u>=0;u--){var z=o[u],A={};A.x=Math.min(m.x,z.x);A.y=Math.min(m.y,
z.y);A.g=Math.max(m.x+m.g,z.x+z.g)-A.x;A.i=Math.max(m.y+m.i,z.y+z.i)-A.y;var A=Math.abs(X(A.g,A.i,m.d.length+2)-r),E={};E.x=Math.min(t.x,z.x);E.y=Math.min(t.y,z.y);E.g=Math.max(t.x+t.g,z.x+z.g)-E.x;E.i=Math.max(t.y+t.i,z.y+z.i)-E.y;z=Math.abs(X(E.g,E.i,t.d.length+2)-v);if(!x||!w||Math.abs(z-A)<w)x=u,w=Math.abs(z-A),s=z<A?t:m}r=o.splice(x,1)[0];m.d.length+o.length+1<=e?(m.d.push(r),Y(m,r)):t.d.length+o.length+1<=e?(t.d.push(r),Y(t,r)):(s.d.push(r),Y(s,r))}g=k;h.length<1&&(d.d.push(k[0]),h.push(d),
g=k[1])}}else Y(d,g),g={x:d.x,y:d.y,g:d.g,i:d.i}}while(h.length>0)}}function c(b,c,d,e){var g=[];if(!Z(b,e))return d;g.push(e.d);do for(var e=g.pop(),f=e.length-1;f>=0;f--){var h=e[f];Z(b,h)&&("nodes"in h?g.push(h.d):"leaf"in h&&(c?d.push(h):d.push(h.Ra)))}while(g.length>0);return d}function d(d,g,f){var h=[],q=[],k=[],o=1;if(!d||!Z(d,f))return k;d={x:d.x,y:d.y,g:d.g,i:d.i,target:g};q.push(f.d.length);h.push(f);do{f=h.pop();g=q.pop()-1;if("target"in d)for(;g>=0;){var m=f.d[g];if(Z(d,m))if(d.target&&
"leaf"in m&&m.Ra===d.target||!d.target&&("leaf"in m||m.x+m.g<=d.x+d.g&&m.x>=d.x&&m.y+m.i<=d.y+d.i&&m.y>=d.y)){"nodes"in m?(k=c(m,!0,[],m),f.d.splice(g,1)):k=f.d.splice(g,1);$(f.d,f);delete d.target;if(f.d.length<e)d.d=c(f,!0,[],f);break}else if("nodes"in m)o+=1,q.push(g),h.push(f),f=m,g=m.d.length;g-=1}else if("nodes"in d){f.d.splice(g+1,1);f.d.length>0&&$(f.d,f);for(g=0;g<d.d.length;g++)b(d.d[g],f);d.d.length=0;h.length==0&&f.d.length<=1?(d.d=c(f,!0,d.d,f),f.d.length=0,h.push(f),q.push(1)):h.length>
0&&f.d.length<e?(d.d=c(f,!0,d.d,f),f.d.length=0):delete d.d}else $(f.d,f);o-=1}while(h.length>0);return k}var e=3,f=6;isNaN(y)||(e=Math.floor(NaN),f=y);var g={x:0,y:0,g:0,i:0,id:"root",d:[]},h=function(){var b={};return function(c){var d=0;c in b?d=b[c]++:b[c]=0;return c+"_"+d}}();X=function(b,c,d){var e=(b+c)/2;b*=c;return b*d/(b/(e*e))};this.Fk=function(){return g};this.el=function(b,c){c||(c=g);var d=c;d.d=b.d;d.x=b.x;d.y=b.y;d.g=b.g;d.i=b.i;return d};this.search=function(){if(arguments.length<
1)throw"Wrong number of arguments. RT.Search requires at least a bounding rectangle.";switch(arguments.length){case 1:arguments[1]=!1;case 2:arguments[2]=[];case 3:arguments[3]=g;default:arguments.length=4}return c.apply(this,arguments)};this.toJSON=function(b,c){var d=[],e=[],f={},k=3,o=1,m="";if(b&&!Z(b,g))return"";c?(k+=4,e.push(c.d.length),d.push(c.d),m+="var main_tree = {x:"+c.x.toFixed()+",y:"+c.y.toFixed()+",w:"+c.g.toFixed()+",h:"+c.i.toFixed()+",nodes:["):(e.push(g.d.length),d.push(g.d),
m+="var main_tree = {x:"+g.x.toFixed()+",y:"+g.y.toFixed()+",w:"+g.g.toFixed()+",h:"+g.i.toFixed()+",nodes:[");do{var s=d.pop(),t=e.pop()-1;for(t>=0&&t<s.length-1&&(m+=",");t>=0;){var r=s[t];if(!b||Z(b,r))if(r.d)if(o>=k){var v=h("saved_subtree");m+="{x:"+r.x.toFixed()+",y:"+r.y.toFixed()+",w:"+r.g.toFixed()+",h:"+r.i.toFixed()+",load:'"+v+".js'}";f[v]=this.toJSON(b,r);t>0&&(m+=",")}else m+="{x:"+r.x.toFixed()+",y:"+r.y.toFixed()+",w:"+r.g.toFixed()+",h:"+r.i.toFixed()+",nodes:[",o+=1,e.push(t),d.push(s),
s=r.d,t=r.d.length;else r.Ra?(v=r.Ra.toJSON?r.Ra.toJSON():JSON.stringify(r.Ra),m+="{x:"+r.x.toFixed()+",y:"+r.y.toFixed()+",w:"+r.g.toFixed()+",h:"+r.i.toFixed()+",leaf:"+v+"}",t>0&&(m+=",")):r.load&&(m+="{x:"+r.x.toFixed()+",y:"+r.y.toFixed()+",w:"+r.g.toFixed()+",h:"+r.i.toFixed()+",load:'"+r.load+"'}",t>0&&(m+=","));t-=1}t<0&&(m+="]}",o-=1)}while(d.length>0);m+=";";for(var w in f)m+="\nvar "+w+" = function(){"+f[w]+" return(main_tree);};";return m};this.remove=function(){if(arguments.length<1)throw"Wrong number of arguments. RT.remove requires at least a bounding rectangle.";
switch(arguments.length){case 1:arguments[1]=!1;case 2:arguments[2]=g;default:arguments.length=3}if(arguments[1]===!1){var b=0,c=[];do b=c.length,c=c.concat(d.apply(this,arguments));while(b!=c.length);return c}else return d.apply(this,arguments)};this.fj=function(c,d){b({x:c.x,y:c.y,g:c.g,i:c.i,Ra:d},g)}}
function ba(b,c,d,e){var f,g,h,j;b.x?(f=b.x,g=b.y,b.g!==0&&!b.g&&b.Va?(h=b.Va-b.x,j=b.rb-b.y):(h=b.g,j=b.i)):(f=b,g=c,h=d,j=e);this.Mj=this.x=f;this.Nj=this.y=g;this.Va=f+h;this.rb=g+j;this.g=h;this.i=j;this.toJSON=function(){return'{"x":'+f.toString()+', "y":'+g.toString()+', "w":'+h.toString()+', "h":'+j.toString()+"}"};this.Tk=function(b){return this.x()<b.Va()&&this.Va()>b.x()&&this.y()<b.rb()&&this.rb()>b.y()};this.expand=function(b){var c=Math.min(this.x(),b.x()),d=Math.min(this.y(),b.y());
h=Math.max(this.Va(),b.Va())-c;j=Math.max(this.rb(),b.rb())-d;f=c;g=d;return this};this.dl=C()}var X;function Z(b,c){return b.x<c.x+c.g&&b.x+b.g>c.x&&b.y<c.y+c.i&&b.y+b.i>c.y}function Y(b,c){var d=Math.min(b.x,c.x),e=Math.min(b.y,c.y);b.g=Math.max(b.x+b.g,c.x+c.g)-d;b.i=Math.max(b.y+b.i,c.y+c.i)-e;b.x=d;b.y=e}function $(b,c){if(!(b.length<1)){c?c.x=b[0].x:c={x:b[0].x,y:b[0].y,g:b[0].g,i:b[0].i};c.y=b[0].y;c.g=b[0].g;c.i=b[0].i;for(var d=b.length-1;d>0;d--)Y(c,b[d])}};/*
 Copyright (c) 2011, Darafei Praliaskouski, Vladimir Agafonkin, Maksim Gurtovenko
 Kothic JS is a full-featured JavaScript map rendering engine using HTML5 Canvas.
 See http://github.com/kothic/kothic-js for more information.
*/
Kothic.Fg=K.p.extend({l:function(){this.Hc={};this.hb=[{message:"initialized",timestamp:+new Date}]},yj:function(b){for(var c in b)b.hasOwnProperty(c)&&(this.Hc[c]=b[c])},oc:function(b){this.hb.push({message:b,timestamp:+new Date})}});
